-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_fm_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    input_fm_ce0 : OUT STD_LOGIC;
    input_fm_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    weights_ce0 : OUT STD_LOGIC;
    weights_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    biases_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    biases_ce0 : OUT STD_LOGIC;
    biases_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_fm_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    output_fm_ce0 : OUT STD_LOGIC;
    output_fm_we0 : OUT STD_LOGIC;
    output_fm_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of conv is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "conv_conv,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.256000,HLS_SYN_LAT=355256001,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=819,HLS_SYN_LUT=1545,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv18_2F440 : STD_LOGIC_VECTOR (17 downto 0) := "101111010001000000";
    constant ap_const_lv18_1 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000001";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv12_BD1 : STD_LOGIC_VECTOR (11 downto 0) := "101111010001";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv13_37 : STD_LOGIC_VECTOR (12 downto 0) := "0000000110111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_37 : STD_LOGIC_VECTOR (5 downto 0) := "110111";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv18_37 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000110111";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln11_fu_212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln11_reg_527 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln9_fu_188_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_1_fu_218_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln9_1_reg_535 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln27_fu_290_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln27_reg_547 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal bitcast_ln9_fu_303_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln9_reg_552 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln11_fu_351_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln11_reg_557 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln11_2_fu_379_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln11_2_reg_562 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_388_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_reg_567 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_fu_473_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln32_1_reg_580 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal select_ln32_fu_461_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln32_reg_585 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_start : STD_LOGIC;
    signal grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_done : STD_LOGIC;
    signal grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_idle : STD_LOGIC;
    signal grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_ready : STD_LOGIC;
    signal grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_weights_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_weights_ce0 : STD_LOGIC;
    signal grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_input_fm_address0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_input_fm_ce0 : STD_LOGIC;
    signal grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_sum_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_sum_1_out_ap_vld : STD_LOGIC;
    signal grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal zext_ln9_fu_226_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_2_fu_469_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal out_c_fu_92 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln13_fu_397_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal out_r_fu_96 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln11_1_fu_359_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten31_fu_100 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln11_3_fu_237_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal n_fu_104 : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten50_fu_108 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln9_1_fu_194_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln9_fu_206_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln11_1_fu_231_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_3_fu_279_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln27_4_fu_286_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln27_3_fu_276_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln32_fu_297_p0 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln32_fu_297_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_s_fu_308_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln13_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln9_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_fu_266_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal and_ln9_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln11_fu_346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln11_fu_340_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_mid_fu_371_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln9_2_fu_316_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal bitcast_ln32_fu_420_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_423_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln32_fu_433_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln32_1_fu_443_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln32_fu_437_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln32_fu_449_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_155_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln32_fu_455_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln32_fu_297_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_473_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_473_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_473_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_473_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal grp_fu_473_p10 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_473_p30 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln32_fu_297_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component conv_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bitcast_ln9 : IN STD_LOGIC_VECTOR (31 downto 0);
        select_ln11_2 : IN STD_LOGIC_VECTOR (7 downto 0);
        sub_ln27 : IN STD_LOGIC_VECTOR (9 downto 0);
        weights_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        weights_ce0 : OUT STD_LOGIC;
        weights_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        tmp_4 : IN STD_LOGIC_VECTOR (7 downto 0);
        input_fm_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        input_fm_ce0 : OUT STD_LOGIC;
        input_fm_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        sum_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        sum_1_out_ap_vld : OUT STD_LOGIC );
    end component;


    component conv_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component conv_mul_7ns_7ns_13_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;


    component conv_ama_addmuladd_13ns_6ns_6ns_6ns_18_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (12 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        din2 : IN STD_LOGIC_VECTOR (5 downto 0);
        din3 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;



begin
    grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142 : component conv_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_start,
        ap_done => grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_done,
        ap_idle => grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_idle,
        ap_ready => grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_ready,
        bitcast_ln9 => bitcast_ln9_reg_552,
        select_ln11_2 => select_ln11_2_reg_562,
        sub_ln27 => sub_ln27_reg_547,
        weights_address0 => grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_weights_address0,
        weights_ce0 => grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_weights_ce0,
        weights_q0 => weights_q0,
        tmp_4 => tmp_4_reg_567,
        input_fm_address0 => grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_input_fm_address0,
        input_fm_ce0 => grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_input_fm_ce0,
        input_fm_q0 => input_fm_q0,
        sum_1_out => grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_sum_1_out,
        sum_1_out_ap_vld => grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_sum_1_out_ap_vld);

    fcmp_32ns_32ns_1_2_no_dsp_1_U20 : component conv_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_sum_1_out,
        din1 => ap_const_lv32_0,
        ce => ap_const_logic_1,
        opcode => ap_const_lv5_2,
        dout => grp_fu_155_p2);

    mul_7ns_7ns_13_1_1_U21 : component conv_mul_7ns_7ns_13_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 7,
        din1_WIDTH => 7,
        dout_WIDTH => 13)
    port map (
        din0 => mul_ln32_fu_297_p0,
        din1 => mul_ln32_fu_297_p1,
        dout => mul_ln32_fu_297_p2);

    ama_addmuladd_13ns_6ns_6ns_6ns_18_4_1_U22 : component conv_ama_addmuladd_13ns_6ns_6ns_6ns_18_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 13,
        din1_WIDTH => 6,
        din2_WIDTH => 6,
        din3_WIDTH => 6,
        dout_WIDTH => 18)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => mul_ln32_fu_297_p2,
        din1 => grp_fu_473_p1,
        din2 => grp_fu_473_p2,
        din3 => grp_fu_473_p3,
        ce => grp_fu_473_ce,
        dout => grp_fu_473_p4);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_ready = ap_const_logic_1)) then 
                    grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten31_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                indvar_flatten31_fu_100 <= ap_const_lv12_0;
            elsif (((icmp_ln9_fu_188_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                indvar_flatten31_fu_100 <= select_ln11_3_fu_237_p3;
            end if; 
        end if;
    end process;

    indvar_flatten50_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                indvar_flatten50_fu_108 <= ap_const_lv18_0;
            elsif (((icmp_ln9_fu_188_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                indvar_flatten50_fu_108 <= add_ln9_1_fu_194_p2;
            end if; 
        end if;
    end process;

    n_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                n_fu_104 <= ap_const_lv7_0;
            elsif (((icmp_ln9_fu_188_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                n_fu_104 <= select_ln9_1_fu_218_p3;
            end if; 
        end if;
    end process;

    out_c_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_c_fu_92 <= ap_const_lv6_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                out_c_fu_92 <= add_ln13_fu_397_p2;
            end if; 
        end if;
    end process;

    out_r_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_r_fu_96 <= ap_const_lv6_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                out_r_fu_96 <= select_ln11_1_fu_359_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                add_ln32_1_reg_580 <= grp_fu_473_p4;
                select_ln32_reg_585 <= select_ln32_fu_461_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                bitcast_ln9_reg_552 <= bitcast_ln9_fu_303_p1;
                    select_ln11_2_reg_562(7 downto 2) <= select_ln11_2_fu_379_p3(7 downto 2);
                select_ln11_reg_557 <= select_ln11_fu_351_p3;
                sub_ln27_reg_547 <= sub_ln27_fu_290_p2;
                    tmp_4_reg_567(7 downto 2) <= tmp_4_fu_388_p3(7 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln9_fu_188_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                icmp_ln11_reg_527 <= icmp_ln11_fu_212_p2;
                select_ln9_1_reg_535 <= select_ln9_1_fu_218_p3;
            end if;
        end if;
    end process;
    select_ln11_2_reg_562(1 downto 0) <= "00";
    tmp_4_reg_567(1 downto 0) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln9_fu_188_p2, grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_done, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln9_fu_188_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    add_ln11_1_fu_231_p2 <= std_logic_vector(unsigned(indvar_flatten31_fu_100) + unsigned(ap_const_lv12_1));
    add_ln11_fu_340_p2 <= std_logic_vector(unsigned(select_ln9_fu_266_p3) + unsigned(ap_const_lv6_1));
    add_ln13_fu_397_p2 <= std_logic_vector(unsigned(select_ln11_fu_351_p3) + unsigned(ap_const_lv6_1));
    add_ln9_1_fu_194_p2 <= std_logic_vector(unsigned(indvar_flatten50_fu_108) + unsigned(ap_const_lv18_1));
    add_ln9_fu_206_p2 <= std_logic_vector(unsigned(n_fu_104) + unsigned(ap_const_lv7_1));
    and_ln32_fu_455_p2 <= (or_ln32_fu_449_p2 and grp_fu_155_p2);
    and_ln9_fu_334_p2 <= (xor_ln9_fu_323_p2 and icmp_ln13_fu_328_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_done)
    begin
        if ((grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state2, icmp_ln9_fu_188_p2)
    begin
        if (((icmp_ln9_fu_188_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln9_fu_188_p2)
    begin
        if (((icmp_ln9_fu_188_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    biases_address0 <= zext_ln9_fu_226_p1(6 - 1 downto 0);

    biases_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            biases_ce0 <= ap_const_logic_1;
        else 
            biases_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln32_fu_420_p1 <= grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_sum_1_out;
    bitcast_ln9_fu_303_p1 <= biases_q0;
    grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_start <= grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_start_reg;

    grp_fu_473_ce_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state6, grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_done, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_ap_done = ap_const_logic_1)))) then 
            grp_fu_473_ce <= ap_const_logic_1;
        else 
            grp_fu_473_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_473_p1 <= grp_fu_473_p10(6 - 1 downto 0);
    grp_fu_473_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln11_1_fu_359_p3),13));
    grp_fu_473_p2 <= ap_const_lv18_37(6 - 1 downto 0);
    grp_fu_473_p3 <= grp_fu_473_p30(6 - 1 downto 0);
    grp_fu_473_p30 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln11_reg_557),18));
    icmp_ln11_fu_212_p2 <= "1" when (indvar_flatten31_fu_100 = ap_const_lv12_BD1) else "0";
    icmp_ln13_fu_328_p2 <= "1" when (out_c_fu_92 = ap_const_lv6_37) else "0";
    icmp_ln32_1_fu_443_p2 <= "1" when (trunc_ln32_fu_433_p1 = ap_const_lv23_0) else "0";
    icmp_ln32_fu_437_p2 <= "0" when (tmp_fu_423_p4 = ap_const_lv8_FF) else "1";
    icmp_ln9_fu_188_p2 <= "1" when (indvar_flatten50_fu_108 = ap_const_lv18_2F440) else "0";
    input_fm_address0 <= grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_input_fm_address0;
    input_fm_ce0 <= grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_input_fm_ce0;
    mul_ln32_fu_297_p0 <= mul_ln32_fu_297_p00(7 - 1 downto 0);
    mul_ln32_fu_297_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln9_1_reg_535),13));
    mul_ln32_fu_297_p1 <= ap_const_lv13_37(7 - 1 downto 0);
    or_ln11_fu_346_p2 <= (icmp_ln11_reg_527 or and_ln9_fu_334_p2);
    or_ln32_fu_449_p2 <= (icmp_ln32_fu_437_p2 or icmp_ln32_1_fu_443_p2);
    output_fm_address0 <= zext_ln32_2_fu_469_p1(18 - 1 downto 0);

    output_fm_ce0_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            output_fm_ce0 <= ap_const_logic_1;
        else 
            output_fm_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_fm_d0 <= select_ln32_reg_585;

    output_fm_we0_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            output_fm_we0 <= ap_const_logic_1;
        else 
            output_fm_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_mid_fu_371_p3 <= (add_ln11_fu_340_p2 & ap_const_lv2_0);
    select_ln11_1_fu_359_p3 <= 
        add_ln11_fu_340_p2 when (and_ln9_fu_334_p2(0) = '1') else 
        select_ln9_fu_266_p3;
    select_ln11_2_fu_379_p3 <= 
        p_mid_fu_371_p3 when (and_ln9_fu_334_p2(0) = '1') else 
        select_ln9_2_fu_316_p3;
    select_ln11_3_fu_237_p3 <= 
        ap_const_lv12_1 when (icmp_ln11_fu_212_p2(0) = '1') else 
        add_ln11_1_fu_231_p2;
    select_ln11_fu_351_p3 <= 
        ap_const_lv6_0 when (or_ln11_fu_346_p2(0) = '1') else 
        out_c_fu_92;
    select_ln32_fu_461_p3 <= 
        bitcast_ln32_fu_420_p1 when (and_ln32_fu_455_p2(0) = '1') else 
        ap_const_lv32_0;
    select_ln9_1_fu_218_p3 <= 
        add_ln9_fu_206_p2 when (icmp_ln11_fu_212_p2(0) = '1') else 
        n_fu_104;
    select_ln9_2_fu_316_p3 <= 
        ap_const_lv8_0 when (icmp_ln11_reg_527(0) = '1') else 
        tmp_s_fu_308_p3;
    select_ln9_fu_266_p3 <= 
        ap_const_lv6_0 when (icmp_ln11_reg_527(0) = '1') else 
        out_r_fu_96;
    sub_ln27_fu_290_p2 <= std_logic_vector(unsigned(zext_ln27_4_fu_286_p1) - unsigned(zext_ln27_3_fu_276_p1));
    tmp_3_fu_279_p3 <= (select_ln9_1_reg_535 & ap_const_lv2_0);
    tmp_4_fu_388_p3 <= (select_ln11_fu_351_p3 & ap_const_lv2_0);
    tmp_fu_423_p4 <= bitcast_ln32_fu_420_p1(30 downto 23);
    tmp_s_fu_308_p3 <= (out_r_fu_96 & ap_const_lv2_0);
    trunc_ln32_fu_433_p1 <= bitcast_ln32_fu_420_p1(23 - 1 downto 0);
    weights_address0 <= grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_weights_address0;
    weights_ce0 <= grp_conv_Pipeline_VITIS_LOOP_17_4_VITIS_LOOP_19_5_VITIS_LOOP_21_6_fu_142_weights_ce0;
    xor_ln9_fu_323_p2 <= (icmp_ln11_reg_527 xor ap_const_lv1_1);
    zext_ln27_3_fu_276_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln9_1_reg_535),10));
    zext_ln27_4_fu_286_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_279_p3),10));
    zext_ln32_2_fu_469_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln32_1_reg_580),64));
    zext_ln9_fu_226_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln9_1_fu_218_p3),64));
end behav;
