// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module matmul_matmul_Pipeline_VITIS_LOOP_59_9 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Matrix_C_BRAM_V_load,
        mul_ln186,
        Matrix_A_BRAM_V_address0,
        Matrix_A_BRAM_V_ce0,
        Matrix_A_BRAM_V_q0,
        Matrix_A_BRAM_V_address1,
        Matrix_A_BRAM_V_ce1,
        Matrix_A_BRAM_V_q1,
        zext_ln57,
        Matrix_B_BRAM_V_address0,
        Matrix_B_BRAM_V_ce0,
        Matrix_B_BRAM_V_q0,
        Matrix_B_BRAM_V_address1,
        Matrix_B_BRAM_V_ce1,
        Matrix_B_BRAM_V_q1,
        conv3_i_188_out,
        conv3_i_188_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] Matrix_C_BRAM_V_load;
input  [13:0] mul_ln186;
output  [13:0] Matrix_A_BRAM_V_address0;
output   Matrix_A_BRAM_V_ce0;
input  [15:0] Matrix_A_BRAM_V_q0;
output  [13:0] Matrix_A_BRAM_V_address1;
output   Matrix_A_BRAM_V_ce1;
input  [15:0] Matrix_A_BRAM_V_q1;
input  [7:0] zext_ln57;
output  [14:0] Matrix_B_BRAM_V_address0;
output   Matrix_B_BRAM_V_ce0;
input  [15:0] Matrix_B_BRAM_V_q0;
output  [14:0] Matrix_B_BRAM_V_address1;
output   Matrix_B_BRAM_V_ce1;
input  [15:0] Matrix_B_BRAM_V_q1;
output  [15:0] conv3_i_188_out;
output   conv3_i_188_out_ap_vld;

reg ap_idle;
reg Matrix_A_BRAM_V_ce0;
reg Matrix_A_BRAM_V_ce1;
reg Matrix_B_BRAM_V_ce0;
reg Matrix_B_BRAM_V_ce1;
reg conv3_i_188_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln59_fu_148_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [14:0] zext_ln57_cast_fu_131_p1;
reg   [14:0] zext_ln57_cast_reg_281;
reg   [7:0] dot_1_reg_287;
reg   [7:0] dot_1_reg_287_pp0_iter1_reg;
reg   [7:0] dot_1_reg_287_pp0_iter2_reg;
reg   [7:0] dot_1_reg_287_pp0_iter3_reg;
reg   [0:0] icmp_ln59_reg_293;
reg   [0:0] icmp_ln59_reg_293_pp0_iter1_reg;
reg   [0:0] icmp_ln59_reg_293_pp0_iter2_reg;
reg   [0:0] icmp_ln59_reg_293_pp0_iter3_reg;
reg   [0:0] icmp_ln59_reg_293_pp0_iter4_reg;
reg   [0:0] icmp_ln59_reg_293_pp0_iter5_reg;
reg   [0:0] icmp_ln59_reg_293_pp0_iter6_reg;
wire   [7:0] or_ln59_fu_154_p2;
reg   [7:0] or_ln59_reg_297;
reg   [7:0] or_ln59_reg_297_pp0_iter1_reg;
reg   [7:0] or_ln59_reg_297_pp0_iter2_reg;
wire   [15:0] grp_fu_245_p2;
wire   [63:0] zext_ln186_6_fu_186_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln186_7_fu_191_p1;
wire   [63:0] zext_ln186_2_fu_203_p1;
wire   [63:0] zext_ln186_3_fu_208_p1;
reg   [15:0] conv3_i_188_fu_48;
(* use_dsp48 = "no" *) wire   [15:0] add_ln840_1_fu_215_p2;
wire    ap_loop_init;
reg   [7:0] dot_fu_52;
wire   [7:0] add_ln59_fu_164_p2;
reg   [7:0] ap_sig_allocacmp_dot_1;
wire    ap_block_pp0_stage0_01001;
wire   [13:0] zext_ln186_5_fu_178_p1;
wire   [13:0] add_ln186_2_fu_181_p2;
wire   [14:0] grp_fu_229_p3;
wire   [13:0] zext_ln186_1_fu_195_p1;
wire   [13:0] add_ln186_fu_198_p2;
wire   [14:0] grp_fu_237_p3;
wire  signed [15:0] add_ln840_1_fu_215_p0;
wire   [15:0] grp_fu_251_p3;
wire   [7:0] grp_fu_229_p0;
wire   [7:0] grp_fu_229_p1;
wire   [7:0] grp_fu_229_p2;
wire   [7:0] grp_fu_237_p0;
wire   [7:0] grp_fu_237_p1;
wire   [7:0] grp_fu_237_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [14:0] grp_fu_229_p00;
wire   [14:0] grp_fu_237_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_done_reg = 1'b0;
end

matmul_mac_muladd_8ns_8ns_8ns_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mac_muladd_8ns_8ns_8ns_15_4_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_229_p0),
    .din1(grp_fu_229_p1),
    .din2(grp_fu_229_p2),
    .ce(1'b1),
    .dout(grp_fu_229_p3)
);

matmul_mac_muladd_8ns_8ns_8ns_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mac_muladd_8ns_8ns_8ns_15_4_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_237_p0),
    .din1(grp_fu_237_p1),
    .din2(grp_fu_237_p2),
    .ce(1'b1),
    .dout(grp_fu_237_p3)
);

matmul_mul_mul_16s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mul_mul_16s_16s_16_4_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Matrix_B_BRAM_V_q1),
    .din1(Matrix_A_BRAM_V_q1),
    .ce(1'b1),
    .dout(grp_fu_245_p2)
);

matmul_mac_muladd_16s_16s_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_16s_16s_16ns_16_4_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Matrix_B_BRAM_V_q0),
    .din1(Matrix_A_BRAM_V_q0),
    .din2(grp_fu_245_p2),
    .ce(1'b1),
    .dout(grp_fu_251_p3)
);

matmul_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            conv3_i_188_fu_48 <= Matrix_C_BRAM_V_load;
        end else if ((ap_enable_reg_pp0_iter8 == 1'b1)) begin
            conv3_i_188_fu_48 <= add_ln840_1_fu_215_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln59_fu_148_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            dot_fu_52 <= add_ln59_fu_164_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            dot_fu_52 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        dot_1_reg_287 <= ap_sig_allocacmp_dot_1;
        dot_1_reg_287_pp0_iter1_reg <= dot_1_reg_287;
        icmp_ln59_reg_293 <= icmp_ln59_fu_148_p2;
        icmp_ln59_reg_293_pp0_iter1_reg <= icmp_ln59_reg_293;
        or_ln59_reg_297_pp0_iter1_reg[7 : 1] <= or_ln59_reg_297[7 : 1];
        zext_ln57_cast_reg_281[7 : 0] <= zext_ln57_cast_fu_131_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        dot_1_reg_287_pp0_iter2_reg <= dot_1_reg_287_pp0_iter1_reg;
        dot_1_reg_287_pp0_iter3_reg <= dot_1_reg_287_pp0_iter2_reg;
        icmp_ln59_reg_293_pp0_iter2_reg <= icmp_ln59_reg_293_pp0_iter1_reg;
        icmp_ln59_reg_293_pp0_iter3_reg <= icmp_ln59_reg_293_pp0_iter2_reg;
        icmp_ln59_reg_293_pp0_iter4_reg <= icmp_ln59_reg_293_pp0_iter3_reg;
        icmp_ln59_reg_293_pp0_iter5_reg <= icmp_ln59_reg_293_pp0_iter4_reg;
        icmp_ln59_reg_293_pp0_iter6_reg <= icmp_ln59_reg_293_pp0_iter5_reg;
        or_ln59_reg_297_pp0_iter2_reg[7 : 1] <= or_ln59_reg_297_pp0_iter1_reg[7 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln59_fu_148_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or_ln59_reg_297[7 : 1] <= or_ln59_fu_154_p2[7 : 1];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        Matrix_A_BRAM_V_ce0 = 1'b1;
    end else begin
        Matrix_A_BRAM_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        Matrix_A_BRAM_V_ce1 = 1'b1;
    end else begin
        Matrix_A_BRAM_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        Matrix_B_BRAM_V_ce0 = 1'b1;
    end else begin
        Matrix_B_BRAM_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        Matrix_B_BRAM_V_ce1 = 1'b1;
    end else begin
        Matrix_B_BRAM_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln59_fu_148_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_dot_1 = 8'd0;
    end else begin
        ap_sig_allocacmp_dot_1 = dot_fu_52;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln59_reg_293_pp0_iter6_reg == 1'd0))) begin
        conv3_i_188_out_ap_vld = 1'b1;
    end else begin
        conv3_i_188_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Matrix_A_BRAM_V_address0 = zext_ln186_2_fu_203_p1;

assign Matrix_A_BRAM_V_address1 = zext_ln186_6_fu_186_p1;

assign Matrix_B_BRAM_V_address0 = zext_ln186_3_fu_208_p1;

assign Matrix_B_BRAM_V_address1 = zext_ln186_7_fu_191_p1;

assign add_ln186_2_fu_181_p2 = (mul_ln186 + zext_ln186_5_fu_178_p1);

assign add_ln186_fu_198_p2 = (mul_ln186 + zext_ln186_1_fu_195_p1);

assign add_ln59_fu_164_p2 = (ap_sig_allocacmp_dot_1 + 8'd2);

assign add_ln840_1_fu_215_p0 = grp_fu_251_p3;

assign add_ln840_1_fu_215_p2 = ($signed(add_ln840_1_fu_215_p0) + $signed(conv3_i_188_fu_48));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign conv3_i_188_out = conv3_i_188_fu_48;

assign grp_fu_229_p0 = grp_fu_229_p00;

assign grp_fu_229_p00 = or_ln59_fu_154_p2;

assign grp_fu_229_p1 = 15'd200;

assign grp_fu_229_p2 = zext_ln57_cast_reg_281;

assign grp_fu_237_p0 = grp_fu_237_p00;

assign grp_fu_237_p00 = dot_1_reg_287;

assign grp_fu_237_p1 = 15'd200;

assign grp_fu_237_p2 = zext_ln57_cast_reg_281;

assign icmp_ln59_fu_148_p2 = ((ap_sig_allocacmp_dot_1 < 8'd150) ? 1'b1 : 1'b0);

assign or_ln59_fu_154_p2 = (ap_sig_allocacmp_dot_1 | 8'd1);

assign zext_ln186_1_fu_195_p1 = dot_1_reg_287_pp0_iter3_reg;

assign zext_ln186_2_fu_203_p1 = add_ln186_fu_198_p2;

assign zext_ln186_3_fu_208_p1 = grp_fu_237_p3;

assign zext_ln186_5_fu_178_p1 = or_ln59_reg_297_pp0_iter2_reg;

assign zext_ln186_6_fu_186_p1 = add_ln186_2_fu_181_p2;

assign zext_ln186_7_fu_191_p1 = grp_fu_229_p3;

assign zext_ln57_cast_fu_131_p1 = zext_ln57;

always @ (posedge ap_clk) begin
    zext_ln57_cast_reg_281[14:8] <= 7'b0000000;
    or_ln59_reg_297[0] <= 1'b1;
    or_ln59_reg_297_pp0_iter1_reg[0] <= 1'b1;
    or_ln59_reg_297_pp0_iter2_reg[0] <= 1'b1;
end

endmodule //matmul_matmul_Pipeline_VITIS_LOOP_59_9
