// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module matmul_matmul_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_mem1_AWVALID,
        m_axi_mem1_AWREADY,
        m_axi_mem1_AWADDR,
        m_axi_mem1_AWID,
        m_axi_mem1_AWLEN,
        m_axi_mem1_AWSIZE,
        m_axi_mem1_AWBURST,
        m_axi_mem1_AWLOCK,
        m_axi_mem1_AWCACHE,
        m_axi_mem1_AWPROT,
        m_axi_mem1_AWQOS,
        m_axi_mem1_AWREGION,
        m_axi_mem1_AWUSER,
        m_axi_mem1_WVALID,
        m_axi_mem1_WREADY,
        m_axi_mem1_WDATA,
        m_axi_mem1_WSTRB,
        m_axi_mem1_WLAST,
        m_axi_mem1_WID,
        m_axi_mem1_WUSER,
        m_axi_mem1_ARVALID,
        m_axi_mem1_ARREADY,
        m_axi_mem1_ARADDR,
        m_axi_mem1_ARID,
        m_axi_mem1_ARLEN,
        m_axi_mem1_ARSIZE,
        m_axi_mem1_ARBURST,
        m_axi_mem1_ARLOCK,
        m_axi_mem1_ARCACHE,
        m_axi_mem1_ARPROT,
        m_axi_mem1_ARQOS,
        m_axi_mem1_ARREGION,
        m_axi_mem1_ARUSER,
        m_axi_mem1_RVALID,
        m_axi_mem1_RREADY,
        m_axi_mem1_RDATA,
        m_axi_mem1_RLAST,
        m_axi_mem1_RID,
        m_axi_mem1_RFIFONUM,
        m_axi_mem1_RUSER,
        m_axi_mem1_RRESP,
        m_axi_mem1_BVALID,
        m_axi_mem1_BREADY,
        m_axi_mem1_BRESP,
        m_axi_mem1_BID,
        m_axi_mem1_BUSER,
        sext_ln19,
        Matrix_A_BRAM_V_address0,
        Matrix_A_BRAM_V_ce0,
        Matrix_A_BRAM_V_we0,
        Matrix_A_BRAM_V_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_mem1_AWVALID;
input   m_axi_mem1_AWREADY;
output  [63:0] m_axi_mem1_AWADDR;
output  [0:0] m_axi_mem1_AWID;
output  [31:0] m_axi_mem1_AWLEN;
output  [2:0] m_axi_mem1_AWSIZE;
output  [1:0] m_axi_mem1_AWBURST;
output  [1:0] m_axi_mem1_AWLOCK;
output  [3:0] m_axi_mem1_AWCACHE;
output  [2:0] m_axi_mem1_AWPROT;
output  [3:0] m_axi_mem1_AWQOS;
output  [3:0] m_axi_mem1_AWREGION;
output  [0:0] m_axi_mem1_AWUSER;
output   m_axi_mem1_WVALID;
input   m_axi_mem1_WREADY;
output  [15:0] m_axi_mem1_WDATA;
output  [1:0] m_axi_mem1_WSTRB;
output   m_axi_mem1_WLAST;
output  [0:0] m_axi_mem1_WID;
output  [0:0] m_axi_mem1_WUSER;
output   m_axi_mem1_ARVALID;
input   m_axi_mem1_ARREADY;
output  [63:0] m_axi_mem1_ARADDR;
output  [0:0] m_axi_mem1_ARID;
output  [31:0] m_axi_mem1_ARLEN;
output  [2:0] m_axi_mem1_ARSIZE;
output  [1:0] m_axi_mem1_ARBURST;
output  [1:0] m_axi_mem1_ARLOCK;
output  [3:0] m_axi_mem1_ARCACHE;
output  [2:0] m_axi_mem1_ARPROT;
output  [3:0] m_axi_mem1_ARQOS;
output  [3:0] m_axi_mem1_ARREGION;
output  [0:0] m_axi_mem1_ARUSER;
input   m_axi_mem1_RVALID;
output   m_axi_mem1_RREADY;
input  [15:0] m_axi_mem1_RDATA;
input   m_axi_mem1_RLAST;
input  [0:0] m_axi_mem1_RID;
input  [9:0] m_axi_mem1_RFIFONUM;
input  [0:0] m_axi_mem1_RUSER;
input  [1:0] m_axi_mem1_RRESP;
input   m_axi_mem1_BVALID;
output   m_axi_mem1_BREADY;
input  [1:0] m_axi_mem1_BRESP;
input  [0:0] m_axi_mem1_BID;
input  [0:0] m_axi_mem1_BUSER;
input  [62:0] sext_ln19;
output  [13:0] Matrix_A_BRAM_V_address0;
output   Matrix_A_BRAM_V_ce0;
output   Matrix_A_BRAM_V_we0;
output  [15:0] Matrix_A_BRAM_V_d0;

reg ap_idle;
reg m_axi_mem1_RREADY;
reg[13:0] Matrix_A_BRAM_V_address0;
reg Matrix_A_BRAM_V_ce0;
reg Matrix_A_BRAM_V_we0;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln19_reg_277;
reg    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    mem1_blk_n_R;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage0;
reg   [15:0] reg_110;
reg    ap_block_pp0_stage1_11001;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln19_fu_143_p2;
wire   [7:0] select_ln19_fu_178_p3;
reg   [7:0] select_ln19_reg_281;
wire   [13:0] mul_ln21_fu_198_p2;
reg   [13:0] mul_ln21_reg_287;
wire   [13:0] add_ln25_1_fu_242_p2;
reg   [13:0] add_ln25_1_reg_293;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln25_1_fu_228_p1;
wire   [63:0] zext_ln25_3_fu_247_p1;
reg   [7:0] c_fu_66;
wire   [7:0] add_ln21_fu_204_p2;
wire    ap_loop_init;
reg   [6:0] r_fu_70;
wire   [6:0] select_ln19_1_fu_186_p3;
reg   [12:0] indvar_flatten_fu_74;
wire   [12:0] add_ln19_1_fu_149_p2;
reg   [12:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [0:0] icmp_ln21_fu_172_p2;
wire   [6:0] add_ln19_fu_166_p2;
wire   [6:0] mul_ln21_fu_198_p0;
wire   [8:0] mul_ln21_fu_198_p1;
wire   [13:0] zext_ln25_fu_220_p1;
wire   [13:0] add_ln25_fu_223_p2;
wire   [7:0] or_ln21_fu_233_p2;
wire   [13:0] zext_ln25_2_fu_238_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [13:0] mul_ln21_fu_198_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

matmul_mul_7ns_9ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 14 ))
mul_7ns_9ns_14_1_1_U1(
    .din0(mul_ln21_fu_198_p0),
    .din1(mul_ln21_fu_198_p1),
    .dout(mul_ln21_fu_198_p2)
);

matmul_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        c_fu_66 <= 8'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln19_reg_277 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        c_fu_66 <= add_ln21_fu_204_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln19_fu_143_p2 == 1'd0))) begin
            indvar_flatten_fu_74 <= add_ln19_1_fu_149_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_74 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        r_fu_70 <= 7'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln19_reg_277 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        r_fu_70 <= select_ln19_1_fu_186_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln25_1_reg_293 <= add_ln25_1_fu_242_p2;
        icmp_ln19_reg_277 <= icmp_ln19_fu_143_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln19_reg_277 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul_ln21_reg_287 <= mul_ln21_fu_198_p2;
        select_ln19_reg_281 <= select_ln19_fu_178_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln19_reg_277 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_110 <= m_axi_mem1_RDATA;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            Matrix_A_BRAM_V_address0 = zext_ln25_3_fu_247_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            Matrix_A_BRAM_V_address0 = zext_ln25_1_fu_228_p1;
        end else begin
            Matrix_A_BRAM_V_address0 = 'bx;
        end
    end else begin
        Matrix_A_BRAM_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        Matrix_A_BRAM_V_ce0 = 1'b1;
    end else begin
        Matrix_A_BRAM_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        Matrix_A_BRAM_V_we0 = 1'b1;
    end else begin
        Matrix_A_BRAM_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (icmp_ln19_reg_277 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 13'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_74;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln19_reg_277 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        m_axi_mem1_RREADY = 1'b1;
    end else begin
        m_axi_mem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1) & (icmp_ln19_reg_277 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        mem1_blk_n_R = m_axi_mem1_RVALID;
    end else begin
        mem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Matrix_A_BRAM_V_d0 = reg_110;

assign add_ln19_1_fu_149_p2 = (ap_sig_allocacmp_indvar_flatten_load + 13'd1);

assign add_ln19_fu_166_p2 = (r_fu_70 + 7'd1);

assign add_ln21_fu_204_p2 = (select_ln19_fu_178_p3 + 8'd2);

assign add_ln25_1_fu_242_p2 = (mul_ln21_reg_287 + zext_ln25_2_fu_238_p1);

assign add_ln25_fu_223_p2 = (mul_ln21_reg_287 + zext_ln25_fu_220_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_mem1_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_mem1_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((icmp_ln19_reg_277 == 1'd0) & (m_axi_mem1_RVALID == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((icmp_ln19_reg_277 == 1'd0) & (m_axi_mem1_RVALID == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((icmp_ln19_reg_277 == 1'd0) & (m_axi_mem1_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (m_axi_mem1_RVALID == 1'b0);
end

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign icmp_ln19_fu_143_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 13'd7500) ? 1'b1 : 1'b0);

assign icmp_ln21_fu_172_p2 = ((c_fu_66 < 8'd150) ? 1'b1 : 1'b0);

assign m_axi_mem1_ARADDR = 64'd0;

assign m_axi_mem1_ARBURST = 2'd0;

assign m_axi_mem1_ARCACHE = 4'd0;

assign m_axi_mem1_ARID = 1'd0;

assign m_axi_mem1_ARLEN = 32'd0;

assign m_axi_mem1_ARLOCK = 2'd0;

assign m_axi_mem1_ARPROT = 3'd0;

assign m_axi_mem1_ARQOS = 4'd0;

assign m_axi_mem1_ARREGION = 4'd0;

assign m_axi_mem1_ARSIZE = 3'd0;

assign m_axi_mem1_ARUSER = 1'd0;

assign m_axi_mem1_ARVALID = 1'b0;

assign m_axi_mem1_AWADDR = 64'd0;

assign m_axi_mem1_AWBURST = 2'd0;

assign m_axi_mem1_AWCACHE = 4'd0;

assign m_axi_mem1_AWID = 1'd0;

assign m_axi_mem1_AWLEN = 32'd0;

assign m_axi_mem1_AWLOCK = 2'd0;

assign m_axi_mem1_AWPROT = 3'd0;

assign m_axi_mem1_AWQOS = 4'd0;

assign m_axi_mem1_AWREGION = 4'd0;

assign m_axi_mem1_AWSIZE = 3'd0;

assign m_axi_mem1_AWUSER = 1'd0;

assign m_axi_mem1_AWVALID = 1'b0;

assign m_axi_mem1_BREADY = 1'b0;

assign m_axi_mem1_WDATA = 16'd0;

assign m_axi_mem1_WID = 1'd0;

assign m_axi_mem1_WLAST = 1'b0;

assign m_axi_mem1_WSTRB = 2'd0;

assign m_axi_mem1_WUSER = 1'd0;

assign m_axi_mem1_WVALID = 1'b0;

assign mul_ln21_fu_198_p0 = mul_ln21_fu_198_p00;

assign mul_ln21_fu_198_p00 = select_ln19_1_fu_186_p3;

assign mul_ln21_fu_198_p1 = 14'd150;

assign or_ln21_fu_233_p2 = (select_ln19_reg_281 | 8'd1);

assign select_ln19_1_fu_186_p3 = ((icmp_ln21_fu_172_p2[0:0] == 1'b1) ? r_fu_70 : add_ln19_fu_166_p2);

assign select_ln19_fu_178_p3 = ((icmp_ln21_fu_172_p2[0:0] == 1'b1) ? c_fu_66 : 8'd0);

assign zext_ln25_1_fu_228_p1 = add_ln25_fu_223_p2;

assign zext_ln25_2_fu_238_p1 = or_ln21_fu_233_p2;

assign zext_ln25_3_fu_247_p1 = add_ln25_1_reg_293;

assign zext_ln25_fu_220_p1 = select_ln19_reg_281;

endmodule //matmul_matmul_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_21_2
