# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/conv_optim/conv_optim.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_optim || ORIG_REF_NAME==conv_optim} -quiet] -quiet

# IP: bd/conv_optim/ip/conv_optim_conv_0_0/conv_optim_conv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_optim_conv_0_0 || ORIG_REF_NAME==conv_optim_conv_0_0} -quiet] -quiet

# IP: bd/conv_optim/ip/conv_optim_processing_system7_0_0/conv_optim_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_optim_processing_system7_0_0 || ORIG_REF_NAME==conv_optim_processing_system7_0_0} -quiet] -quiet

# IP: bd/conv_optim/ip/conv_optim_auto_pc_0/conv_optim_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_optim_auto_pc_0 || ORIG_REF_NAME==conv_optim_auto_pc_0} -quiet] -quiet

# IP: bd/conv_optim/ip/conv_optim_ps7_0_axi_periph_0/conv_optim_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_optim_ps7_0_axi_periph_0 || ORIG_REF_NAME==conv_optim_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/conv_optim/ip/conv_optim_rst_ps7_0_100M_0/conv_optim_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_optim_rst_ps7_0_100M_0 || ORIG_REF_NAME==conv_optim_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/conv_optim/ip/conv_optim_auto_pc_1/conv_optim_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_optim_auto_pc_1 || ORIG_REF_NAME==conv_optim_auto_pc_1} -quiet] -quiet

# IP: bd/conv_optim/ip/conv_optim_auto_us_0/conv_optim_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_optim_auto_us_0 || ORIG_REF_NAME==conv_optim_auto_us_0} -quiet] -quiet

# IP: bd/conv_optim/ip/conv_optim_axi_mem_intercon_0/conv_optim_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_optim_axi_mem_intercon_0 || ORIG_REF_NAME==conv_optim_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/conv_optim/ip/conv_optim_auto_pc_2/conv_optim_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_optim_auto_pc_2 || ORIG_REF_NAME==conv_optim_auto_pc_2} -quiet] -quiet

# IP: bd/conv_optim/ip/conv_optim_auto_us_1/conv_optim_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_optim_auto_us_1 || ORIG_REF_NAME==conv_optim_auto_us_1} -quiet] -quiet

# IP: bd/conv_optim/ip/conv_optim_axi_mem_intercon_1_0/conv_optim_axi_mem_intercon_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_optim_axi_mem_intercon_1_0 || ORIG_REF_NAME==conv_optim_axi_mem_intercon_1_0} -quiet] -quiet

# XDC: /home/ykim131_588fa26/Desktop/ECE588/ECE588_fa2026_Lab03/vivado/conv_optim/conv_optim.gen/sources_1/bd/conv_optim/conv_optim_ooc.xdc
