// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv_conv_Pipeline_VITIS_LOOP_85_13_VITIS_LOOP_87_14 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_mem1_AWVALID,
        m_axi_mem1_AWREADY,
        m_axi_mem1_AWADDR,
        m_axi_mem1_AWID,
        m_axi_mem1_AWLEN,
        m_axi_mem1_AWSIZE,
        m_axi_mem1_AWBURST,
        m_axi_mem1_AWLOCK,
        m_axi_mem1_AWCACHE,
        m_axi_mem1_AWPROT,
        m_axi_mem1_AWQOS,
        m_axi_mem1_AWREGION,
        m_axi_mem1_AWUSER,
        m_axi_mem1_WVALID,
        m_axi_mem1_WREADY,
        m_axi_mem1_WDATA,
        m_axi_mem1_WSTRB,
        m_axi_mem1_WLAST,
        m_axi_mem1_WID,
        m_axi_mem1_WUSER,
        m_axi_mem1_ARVALID,
        m_axi_mem1_ARREADY,
        m_axi_mem1_ARADDR,
        m_axi_mem1_ARID,
        m_axi_mem1_ARLEN,
        m_axi_mem1_ARSIZE,
        m_axi_mem1_ARBURST,
        m_axi_mem1_ARLOCK,
        m_axi_mem1_ARCACHE,
        m_axi_mem1_ARPROT,
        m_axi_mem1_ARQOS,
        m_axi_mem1_ARREGION,
        m_axi_mem1_ARUSER,
        m_axi_mem1_RVALID,
        m_axi_mem1_RREADY,
        m_axi_mem1_RDATA,
        m_axi_mem1_RLAST,
        m_axi_mem1_RID,
        m_axi_mem1_RFIFONUM,
        m_axi_mem1_RUSER,
        m_axi_mem1_RRESP,
        m_axi_mem1_BVALID,
        m_axi_mem1_BREADY,
        m_axi_mem1_BRESP,
        m_axi_mem1_BID,
        m_axi_mem1_BUSER,
        sext_ln23,
        local_output_address0,
        local_output_ce0,
        local_output_q0,
        local_output_1_address0,
        local_output_1_ce0,
        local_output_1_q0,
        local_output_2_address0,
        local_output_2_ce0,
        local_output_2_q0,
        local_output_3_address0,
        local_output_3_ce0,
        local_output_3_q0,
        local_output_4_address0,
        local_output_4_ce0,
        local_output_4_q0,
        local_output_5_address0,
        local_output_5_ce0,
        local_output_5_q0,
        local_output_6_address0,
        local_output_6_ce0,
        local_output_6_q0,
        local_output_7_address0,
        local_output_7_ce0,
        local_output_7_q0,
        local_output_8_address0,
        local_output_8_ce0,
        local_output_8_q0,
        local_output_9_address0,
        local_output_9_ce0,
        local_output_9_q0,
        local_output_10_address0,
        local_output_10_ce0,
        local_output_10_q0,
        local_output_11_address0,
        local_output_11_ce0,
        local_output_11_q0,
        local_output_12_address0,
        local_output_12_ce0,
        local_output_12_q0,
        local_output_13_address0,
        local_output_13_ce0,
        local_output_13_q0,
        local_output_14_address0,
        local_output_14_ce0,
        local_output_14_q0,
        local_output_15_address0,
        local_output_15_ce0,
        local_output_15_q0,
        local_output_16_address0,
        local_output_16_ce0,
        local_output_16_q0,
        local_output_17_address0,
        local_output_17_ce0,
        local_output_17_q0,
        local_output_18_address0,
        local_output_18_ce0,
        local_output_18_q0,
        local_output_19_address0,
        local_output_19_ce0,
        local_output_19_q0,
        local_output_20_address0,
        local_output_20_ce0,
        local_output_20_q0,
        local_output_21_address0,
        local_output_21_ce0,
        local_output_21_q0,
        local_output_22_address0,
        local_output_22_ce0,
        local_output_22_q0,
        local_output_23_address0,
        local_output_23_ce0,
        local_output_23_q0,
        local_output_24_address0,
        local_output_24_ce0,
        local_output_24_q0,
        local_output_25_address0,
        local_output_25_ce0,
        local_output_25_q0,
        local_output_26_address0,
        local_output_26_ce0,
        local_output_26_q0,
        local_output_27_address0,
        local_output_27_ce0,
        local_output_27_q0,
        local_output_28_address0,
        local_output_28_ce0,
        local_output_28_q0,
        local_output_29_address0,
        local_output_29_ce0,
        local_output_29_q0,
        local_output_30_address0,
        local_output_30_ce0,
        local_output_30_q0,
        local_output_31_address0,
        local_output_31_ce0,
        local_output_31_q0,
        local_output_32_address0,
        local_output_32_ce0,
        local_output_32_q0,
        local_output_33_address0,
        local_output_33_ce0,
        local_output_33_q0,
        local_output_34_address0,
        local_output_34_ce0,
        local_output_34_q0,
        local_output_35_address0,
        local_output_35_ce0,
        local_output_35_q0,
        local_output_36_address0,
        local_output_36_ce0,
        local_output_36_q0,
        local_output_37_address0,
        local_output_37_ce0,
        local_output_37_q0,
        local_output_38_address0,
        local_output_38_ce0,
        local_output_38_q0,
        local_output_39_address0,
        local_output_39_ce0,
        local_output_39_q0,
        local_output_40_address0,
        local_output_40_ce0,
        local_output_40_q0,
        local_output_41_address0,
        local_output_41_ce0,
        local_output_41_q0,
        local_output_42_address0,
        local_output_42_ce0,
        local_output_42_q0,
        local_output_43_address0,
        local_output_43_ce0,
        local_output_43_q0,
        local_output_44_address0,
        local_output_44_ce0,
        local_output_44_q0,
        local_output_45_address0,
        local_output_45_ce0,
        local_output_45_q0,
        local_output_46_address0,
        local_output_46_ce0,
        local_output_46_q0,
        local_output_47_address0,
        local_output_47_ce0,
        local_output_47_q0,
        local_output_48_address0,
        local_output_48_ce0,
        local_output_48_q0,
        local_output_49_address0,
        local_output_49_ce0,
        local_output_49_q0,
        local_output_50_address0,
        local_output_50_ce0,
        local_output_50_q0,
        local_output_51_address0,
        local_output_51_ce0,
        local_output_51_q0,
        local_output_52_address0,
        local_output_52_ce0,
        local_output_52_q0,
        local_output_53_address0,
        local_output_53_ce0,
        local_output_53_q0,
        local_output_54_address0,
        local_output_54_ce0,
        local_output_54_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_mem1_AWVALID;
input   m_axi_mem1_AWREADY;
output  [63:0] m_axi_mem1_AWADDR;
output  [0:0] m_axi_mem1_AWID;
output  [31:0] m_axi_mem1_AWLEN;
output  [2:0] m_axi_mem1_AWSIZE;
output  [1:0] m_axi_mem1_AWBURST;
output  [1:0] m_axi_mem1_AWLOCK;
output  [3:0] m_axi_mem1_AWCACHE;
output  [2:0] m_axi_mem1_AWPROT;
output  [3:0] m_axi_mem1_AWQOS;
output  [3:0] m_axi_mem1_AWREGION;
output  [0:0] m_axi_mem1_AWUSER;
output   m_axi_mem1_WVALID;
input   m_axi_mem1_WREADY;
output  [31:0] m_axi_mem1_WDATA;
output  [3:0] m_axi_mem1_WSTRB;
output   m_axi_mem1_WLAST;
output  [0:0] m_axi_mem1_WID;
output  [0:0] m_axi_mem1_WUSER;
output   m_axi_mem1_ARVALID;
input   m_axi_mem1_ARREADY;
output  [63:0] m_axi_mem1_ARADDR;
output  [0:0] m_axi_mem1_ARID;
output  [31:0] m_axi_mem1_ARLEN;
output  [2:0] m_axi_mem1_ARSIZE;
output  [1:0] m_axi_mem1_ARBURST;
output  [1:0] m_axi_mem1_ARLOCK;
output  [3:0] m_axi_mem1_ARCACHE;
output  [2:0] m_axi_mem1_ARPROT;
output  [3:0] m_axi_mem1_ARQOS;
output  [3:0] m_axi_mem1_ARREGION;
output  [0:0] m_axi_mem1_ARUSER;
input   m_axi_mem1_RVALID;
output   m_axi_mem1_RREADY;
input  [31:0] m_axi_mem1_RDATA;
input   m_axi_mem1_RLAST;
input  [0:0] m_axi_mem1_RID;
input  [8:0] m_axi_mem1_RFIFONUM;
input  [0:0] m_axi_mem1_RUSER;
input  [1:0] m_axi_mem1_RRESP;
input   m_axi_mem1_BVALID;
output   m_axi_mem1_BREADY;
input  [1:0] m_axi_mem1_BRESP;
input  [0:0] m_axi_mem1_BID;
input  [0:0] m_axi_mem1_BUSER;
input  [61:0] sext_ln23;
output  [5:0] local_output_address0;
output   local_output_ce0;
input  [31:0] local_output_q0;
output  [5:0] local_output_1_address0;
output   local_output_1_ce0;
input  [31:0] local_output_1_q0;
output  [5:0] local_output_2_address0;
output   local_output_2_ce0;
input  [31:0] local_output_2_q0;
output  [5:0] local_output_3_address0;
output   local_output_3_ce0;
input  [31:0] local_output_3_q0;
output  [5:0] local_output_4_address0;
output   local_output_4_ce0;
input  [31:0] local_output_4_q0;
output  [5:0] local_output_5_address0;
output   local_output_5_ce0;
input  [31:0] local_output_5_q0;
output  [5:0] local_output_6_address0;
output   local_output_6_ce0;
input  [31:0] local_output_6_q0;
output  [5:0] local_output_7_address0;
output   local_output_7_ce0;
input  [31:0] local_output_7_q0;
output  [5:0] local_output_8_address0;
output   local_output_8_ce0;
input  [31:0] local_output_8_q0;
output  [5:0] local_output_9_address0;
output   local_output_9_ce0;
input  [31:0] local_output_9_q0;
output  [5:0] local_output_10_address0;
output   local_output_10_ce0;
input  [31:0] local_output_10_q0;
output  [5:0] local_output_11_address0;
output   local_output_11_ce0;
input  [31:0] local_output_11_q0;
output  [5:0] local_output_12_address0;
output   local_output_12_ce0;
input  [31:0] local_output_12_q0;
output  [5:0] local_output_13_address0;
output   local_output_13_ce0;
input  [31:0] local_output_13_q0;
output  [5:0] local_output_14_address0;
output   local_output_14_ce0;
input  [31:0] local_output_14_q0;
output  [5:0] local_output_15_address0;
output   local_output_15_ce0;
input  [31:0] local_output_15_q0;
output  [5:0] local_output_16_address0;
output   local_output_16_ce0;
input  [31:0] local_output_16_q0;
output  [5:0] local_output_17_address0;
output   local_output_17_ce0;
input  [31:0] local_output_17_q0;
output  [5:0] local_output_18_address0;
output   local_output_18_ce0;
input  [31:0] local_output_18_q0;
output  [5:0] local_output_19_address0;
output   local_output_19_ce0;
input  [31:0] local_output_19_q0;
output  [5:0] local_output_20_address0;
output   local_output_20_ce0;
input  [31:0] local_output_20_q0;
output  [5:0] local_output_21_address0;
output   local_output_21_ce0;
input  [31:0] local_output_21_q0;
output  [5:0] local_output_22_address0;
output   local_output_22_ce0;
input  [31:0] local_output_22_q0;
output  [5:0] local_output_23_address0;
output   local_output_23_ce0;
input  [31:0] local_output_23_q0;
output  [5:0] local_output_24_address0;
output   local_output_24_ce0;
input  [31:0] local_output_24_q0;
output  [5:0] local_output_25_address0;
output   local_output_25_ce0;
input  [31:0] local_output_25_q0;
output  [5:0] local_output_26_address0;
output   local_output_26_ce0;
input  [31:0] local_output_26_q0;
output  [5:0] local_output_27_address0;
output   local_output_27_ce0;
input  [31:0] local_output_27_q0;
output  [5:0] local_output_28_address0;
output   local_output_28_ce0;
input  [31:0] local_output_28_q0;
output  [5:0] local_output_29_address0;
output   local_output_29_ce0;
input  [31:0] local_output_29_q0;
output  [5:0] local_output_30_address0;
output   local_output_30_ce0;
input  [31:0] local_output_30_q0;
output  [5:0] local_output_31_address0;
output   local_output_31_ce0;
input  [31:0] local_output_31_q0;
output  [5:0] local_output_32_address0;
output   local_output_32_ce0;
input  [31:0] local_output_32_q0;
output  [5:0] local_output_33_address0;
output   local_output_33_ce0;
input  [31:0] local_output_33_q0;
output  [5:0] local_output_34_address0;
output   local_output_34_ce0;
input  [31:0] local_output_34_q0;
output  [5:0] local_output_35_address0;
output   local_output_35_ce0;
input  [31:0] local_output_35_q0;
output  [5:0] local_output_36_address0;
output   local_output_36_ce0;
input  [31:0] local_output_36_q0;
output  [5:0] local_output_37_address0;
output   local_output_37_ce0;
input  [31:0] local_output_37_q0;
output  [5:0] local_output_38_address0;
output   local_output_38_ce0;
input  [31:0] local_output_38_q0;
output  [5:0] local_output_39_address0;
output   local_output_39_ce0;
input  [31:0] local_output_39_q0;
output  [5:0] local_output_40_address0;
output   local_output_40_ce0;
input  [31:0] local_output_40_q0;
output  [5:0] local_output_41_address0;
output   local_output_41_ce0;
input  [31:0] local_output_41_q0;
output  [5:0] local_output_42_address0;
output   local_output_42_ce0;
input  [31:0] local_output_42_q0;
output  [5:0] local_output_43_address0;
output   local_output_43_ce0;
input  [31:0] local_output_43_q0;
output  [5:0] local_output_44_address0;
output   local_output_44_ce0;
input  [31:0] local_output_44_q0;
output  [5:0] local_output_45_address0;
output   local_output_45_ce0;
input  [31:0] local_output_45_q0;
output  [5:0] local_output_46_address0;
output   local_output_46_ce0;
input  [31:0] local_output_46_q0;
output  [5:0] local_output_47_address0;
output   local_output_47_ce0;
input  [31:0] local_output_47_q0;
output  [5:0] local_output_48_address0;
output   local_output_48_ce0;
input  [31:0] local_output_48_q0;
output  [5:0] local_output_49_address0;
output   local_output_49_ce0;
input  [31:0] local_output_49_q0;
output  [5:0] local_output_50_address0;
output   local_output_50_ce0;
input  [31:0] local_output_50_q0;
output  [5:0] local_output_51_address0;
output   local_output_51_ce0;
input  [31:0] local_output_51_q0;
output  [5:0] local_output_52_address0;
output   local_output_52_ce0;
input  [31:0] local_output_52_q0;
output  [5:0] local_output_53_address0;
output   local_output_53_ce0;
input  [31:0] local_output_53_q0;
output  [5:0] local_output_54_address0;
output   local_output_54_ce0;
input  [31:0] local_output_54_q0;

reg ap_idle;
reg m_axi_mem1_WVALID;
reg local_output_ce0;
reg local_output_1_ce0;
reg local_output_2_ce0;
reg local_output_3_ce0;
reg local_output_4_ce0;
reg local_output_5_ce0;
reg local_output_6_ce0;
reg local_output_7_ce0;
reg local_output_8_ce0;
reg local_output_9_ce0;
reg local_output_10_ce0;
reg local_output_11_ce0;
reg local_output_12_ce0;
reg local_output_13_ce0;
reg local_output_14_ce0;
reg local_output_15_ce0;
reg local_output_16_ce0;
reg local_output_17_ce0;
reg local_output_18_ce0;
reg local_output_19_ce0;
reg local_output_20_ce0;
reg local_output_21_ce0;
reg local_output_22_ce0;
reg local_output_23_ce0;
reg local_output_24_ce0;
reg local_output_25_ce0;
reg local_output_26_ce0;
reg local_output_27_ce0;
reg local_output_28_ce0;
reg local_output_29_ce0;
reg local_output_30_ce0;
reg local_output_31_ce0;
reg local_output_32_ce0;
reg local_output_33_ce0;
reg local_output_34_ce0;
reg local_output_35_ce0;
reg local_output_36_ce0;
reg local_output_37_ce0;
reg local_output_38_ce0;
reg local_output_39_ce0;
reg local_output_40_ce0;
reg local_output_41_ce0;
reg local_output_42_ce0;
reg local_output_43_ce0;
reg local_output_44_ce0;
reg local_output_45_ce0;
reg local_output_46_ce0;
reg local_output_47_ce0;
reg local_output_48_ce0;
reg local_output_49_ce0;
reg local_output_50_ce0;
reg local_output_51_ce0;
reg local_output_52_ce0;
reg local_output_53_ce0;
reg local_output_54_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln85_fu_950_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    mem1_blk_n_W;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln85_reg_1271;
reg   [0:0] icmp_ln85_reg_1271_pp0_iter1_reg;
reg   [0:0] icmp_ln85_reg_1271_pp0_iter2_reg;
wire   [5:0] select_ln85_fu_974_p3;
reg   [5:0] select_ln85_reg_1275;
wire   [31:0] result_fu_1076_p57;
reg   [31:0] result_reg_1555;
reg   [31:0] result_reg_1555_pp0_iter2_reg;
wire   [31:0] select_ln92_fu_1237_p3;
reg   [31:0] select_ln92_reg_1566;
reg    ap_condition_exit_pp0_iter3_stage0;
wire   [63:0] zext_ln85_fu_996_p1;
wire    ap_block_pp0_stage0_01001;
reg   [5:0] out_c_fu_182;
wire   [5:0] add_ln87_fu_1055_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_out_c_load;
reg   [5:0] out_r_fu_186;
wire   [5:0] select_ln85_1_fu_988_p3;
reg   [5:0] ap_sig_allocacmp_out_r_load;
reg   [11:0] indvar_flatten613_fu_190;
wire   [11:0] add_ln85_fu_956_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten613_load;
wire   [0:0] icmp_ln87_fu_968_p2;
wire   [5:0] add_ln85_1_fu_982_p2;
wire   [31:0] bitcast_ln93_fu_1196_p1;
wire   [7:0] tmp_2_fu_1199_p4;
wire   [22:0] trunc_ln93_fu_1209_p1;
wire   [0:0] icmp_ln93_1_fu_1219_p2;
wire   [0:0] icmp_ln93_fu_1213_p2;
wire   [0:0] or_ln93_fu_1225_p2;
wire   [0:0] grp_fu_923_p2;
wire   [0:0] and_ln93_fu_1231_p2;
reg    grp_fu_923_ce;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

conv_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U549(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(result_reg_1555),
    .din1(32'd0),
    .ce(grp_fu_923_ce),
    .opcode(5'd2),
    .dout(grp_fu_923_p2)
);

conv_mux_556_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
mux_556_32_1_1_U550(
    .din0(local_output_q0),
    .din1(local_output_1_q0),
    .din2(local_output_2_q0),
    .din3(local_output_3_q0),
    .din4(local_output_4_q0),
    .din5(local_output_5_q0),
    .din6(local_output_6_q0),
    .din7(local_output_7_q0),
    .din8(local_output_8_q0),
    .din9(local_output_9_q0),
    .din10(local_output_10_q0),
    .din11(local_output_11_q0),
    .din12(local_output_12_q0),
    .din13(local_output_13_q0),
    .din14(local_output_14_q0),
    .din15(local_output_15_q0),
    .din16(local_output_16_q0),
    .din17(local_output_17_q0),
    .din18(local_output_18_q0),
    .din19(local_output_19_q0),
    .din20(local_output_20_q0),
    .din21(local_output_21_q0),
    .din22(local_output_22_q0),
    .din23(local_output_23_q0),
    .din24(local_output_24_q0),
    .din25(local_output_25_q0),
    .din26(local_output_26_q0),
    .din27(local_output_27_q0),
    .din28(local_output_28_q0),
    .din29(local_output_29_q0),
    .din30(local_output_30_q0),
    .din31(local_output_31_q0),
    .din32(local_output_32_q0),
    .din33(local_output_33_q0),
    .din34(local_output_34_q0),
    .din35(local_output_35_q0),
    .din36(local_output_36_q0),
    .din37(local_output_37_q0),
    .din38(local_output_38_q0),
    .din39(local_output_39_q0),
    .din40(local_output_40_q0),
    .din41(local_output_41_q0),
    .din42(local_output_42_q0),
    .din43(local_output_43_q0),
    .din44(local_output_44_q0),
    .din45(local_output_45_q0),
    .din46(local_output_46_q0),
    .din47(local_output_47_q0),
    .din48(local_output_48_q0),
    .din49(local_output_49_q0),
    .din50(local_output_50_q0),
    .din51(local_output_51_q0),
    .din52(local_output_52_q0),
    .din53(local_output_53_q0),
    .din54(local_output_54_q0),
    .din55(select_ln85_reg_1275),
    .dout(result_fu_1076_p57)
);

conv_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter3_stage0)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln85_fu_950_p2 == 1'd0))) begin
            indvar_flatten613_fu_190 <= add_ln85_fu_956_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten613_fu_190 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln85_fu_950_p2 == 1'd0))) begin
            out_c_fu_182 <= add_ln87_fu_1055_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            out_c_fu_182 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln85_fu_950_p2 == 1'd0))) begin
            out_r_fu_186 <= select_ln85_1_fu_988_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            out_r_fu_186 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln85_reg_1271 <= icmp_ln85_fu_950_p2;
        icmp_ln85_reg_1271_pp0_iter1_reg <= icmp_ln85_reg_1271;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln85_reg_1271_pp0_iter2_reg <= icmp_ln85_reg_1271_pp0_iter1_reg;
        result_reg_1555_pp0_iter2_reg <= result_reg_1555;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln85_reg_1271 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        result_reg_1555 <= result_fu_1076_p57;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln85_fu_950_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        select_ln85_reg_1275 <= select_ln85_fu_974_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln85_reg_1271_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        select_ln92_reg_1566 <= select_ln92_fu_1237_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln85_fu_950_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln85_reg_1271_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten613_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten613_load = indvar_flatten613_fu_190;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_out_c_load = 6'd0;
    end else begin
        ap_sig_allocacmp_out_c_load = out_c_fu_182;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_out_r_load = 6'd0;
    end else begin
        ap_sig_allocacmp_out_r_load = out_r_fu_186;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_923_ce = 1'b1;
    end else begin
        grp_fu_923_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_10_ce0 = 1'b1;
    end else begin
        local_output_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_11_ce0 = 1'b1;
    end else begin
        local_output_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_12_ce0 = 1'b1;
    end else begin
        local_output_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_13_ce0 = 1'b1;
    end else begin
        local_output_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_14_ce0 = 1'b1;
    end else begin
        local_output_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_15_ce0 = 1'b1;
    end else begin
        local_output_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_16_ce0 = 1'b1;
    end else begin
        local_output_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_17_ce0 = 1'b1;
    end else begin
        local_output_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_18_ce0 = 1'b1;
    end else begin
        local_output_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_19_ce0 = 1'b1;
    end else begin
        local_output_19_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_1_ce0 = 1'b1;
    end else begin
        local_output_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_20_ce0 = 1'b1;
    end else begin
        local_output_20_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_21_ce0 = 1'b1;
    end else begin
        local_output_21_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_22_ce0 = 1'b1;
    end else begin
        local_output_22_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_23_ce0 = 1'b1;
    end else begin
        local_output_23_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_24_ce0 = 1'b1;
    end else begin
        local_output_24_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_25_ce0 = 1'b1;
    end else begin
        local_output_25_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_26_ce0 = 1'b1;
    end else begin
        local_output_26_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_27_ce0 = 1'b1;
    end else begin
        local_output_27_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_28_ce0 = 1'b1;
    end else begin
        local_output_28_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_29_ce0 = 1'b1;
    end else begin
        local_output_29_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_2_ce0 = 1'b1;
    end else begin
        local_output_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_30_ce0 = 1'b1;
    end else begin
        local_output_30_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_31_ce0 = 1'b1;
    end else begin
        local_output_31_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_32_ce0 = 1'b1;
    end else begin
        local_output_32_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_33_ce0 = 1'b1;
    end else begin
        local_output_33_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_34_ce0 = 1'b1;
    end else begin
        local_output_34_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_35_ce0 = 1'b1;
    end else begin
        local_output_35_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_36_ce0 = 1'b1;
    end else begin
        local_output_36_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_37_ce0 = 1'b1;
    end else begin
        local_output_37_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_38_ce0 = 1'b1;
    end else begin
        local_output_38_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_39_ce0 = 1'b1;
    end else begin
        local_output_39_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_3_ce0 = 1'b1;
    end else begin
        local_output_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_40_ce0 = 1'b1;
    end else begin
        local_output_40_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_41_ce0 = 1'b1;
    end else begin
        local_output_41_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_42_ce0 = 1'b1;
    end else begin
        local_output_42_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_43_ce0 = 1'b1;
    end else begin
        local_output_43_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_44_ce0 = 1'b1;
    end else begin
        local_output_44_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_45_ce0 = 1'b1;
    end else begin
        local_output_45_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_46_ce0 = 1'b1;
    end else begin
        local_output_46_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_47_ce0 = 1'b1;
    end else begin
        local_output_47_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_48_ce0 = 1'b1;
    end else begin
        local_output_48_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_49_ce0 = 1'b1;
    end else begin
        local_output_49_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_4_ce0 = 1'b1;
    end else begin
        local_output_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_50_ce0 = 1'b1;
    end else begin
        local_output_50_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_51_ce0 = 1'b1;
    end else begin
        local_output_51_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_52_ce0 = 1'b1;
    end else begin
        local_output_52_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_53_ce0 = 1'b1;
    end else begin
        local_output_53_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_54_ce0 = 1'b1;
    end else begin
        local_output_54_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_5_ce0 = 1'b1;
    end else begin
        local_output_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_6_ce0 = 1'b1;
    end else begin
        local_output_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_7_ce0 = 1'b1;
    end else begin
        local_output_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_8_ce0 = 1'b1;
    end else begin
        local_output_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_9_ce0 = 1'b1;
    end else begin
        local_output_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_output_ce0 = 1'b1;
    end else begin
        local_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_mem1_WVALID = 1'b1;
    end else begin
        m_axi_mem1_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        mem1_blk_n_W = m_axi_mem1_WREADY;
    end else begin
        mem1_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln85_1_fu_982_p2 = (ap_sig_allocacmp_out_r_load + 6'd1);

assign add_ln85_fu_956_p2 = (ap_sig_allocacmp_indvar_flatten613_load + 12'd1);

assign add_ln87_fu_1055_p2 = (select_ln85_fu_974_p3 + 6'd1);

assign and_ln93_fu_1231_p2 = (or_ln93_fu_1225_p2 & grp_fu_923_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_mem1_WREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_mem1_WREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bitcast_ln93_fu_1196_p1 = result_reg_1555_pp0_iter2_reg;

assign icmp_ln85_fu_950_p2 = ((ap_sig_allocacmp_indvar_flatten613_load == 12'd3025) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_968_p2 = ((ap_sig_allocacmp_out_c_load == 6'd55) ? 1'b1 : 1'b0);

assign icmp_ln93_1_fu_1219_p2 = ((trunc_ln93_fu_1209_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln93_fu_1213_p2 = ((tmp_2_fu_1199_p4 != 8'd255) ? 1'b1 : 1'b0);

assign local_output_10_address0 = zext_ln85_fu_996_p1;

assign local_output_11_address0 = zext_ln85_fu_996_p1;

assign local_output_12_address0 = zext_ln85_fu_996_p1;

assign local_output_13_address0 = zext_ln85_fu_996_p1;

assign local_output_14_address0 = zext_ln85_fu_996_p1;

assign local_output_15_address0 = zext_ln85_fu_996_p1;

assign local_output_16_address0 = zext_ln85_fu_996_p1;

assign local_output_17_address0 = zext_ln85_fu_996_p1;

assign local_output_18_address0 = zext_ln85_fu_996_p1;

assign local_output_19_address0 = zext_ln85_fu_996_p1;

assign local_output_1_address0 = zext_ln85_fu_996_p1;

assign local_output_20_address0 = zext_ln85_fu_996_p1;

assign local_output_21_address0 = zext_ln85_fu_996_p1;

assign local_output_22_address0 = zext_ln85_fu_996_p1;

assign local_output_23_address0 = zext_ln85_fu_996_p1;

assign local_output_24_address0 = zext_ln85_fu_996_p1;

assign local_output_25_address0 = zext_ln85_fu_996_p1;

assign local_output_26_address0 = zext_ln85_fu_996_p1;

assign local_output_27_address0 = zext_ln85_fu_996_p1;

assign local_output_28_address0 = zext_ln85_fu_996_p1;

assign local_output_29_address0 = zext_ln85_fu_996_p1;

assign local_output_2_address0 = zext_ln85_fu_996_p1;

assign local_output_30_address0 = zext_ln85_fu_996_p1;

assign local_output_31_address0 = zext_ln85_fu_996_p1;

assign local_output_32_address0 = zext_ln85_fu_996_p1;

assign local_output_33_address0 = zext_ln85_fu_996_p1;

assign local_output_34_address0 = zext_ln85_fu_996_p1;

assign local_output_35_address0 = zext_ln85_fu_996_p1;

assign local_output_36_address0 = zext_ln85_fu_996_p1;

assign local_output_37_address0 = zext_ln85_fu_996_p1;

assign local_output_38_address0 = zext_ln85_fu_996_p1;

assign local_output_39_address0 = zext_ln85_fu_996_p1;

assign local_output_3_address0 = zext_ln85_fu_996_p1;

assign local_output_40_address0 = zext_ln85_fu_996_p1;

assign local_output_41_address0 = zext_ln85_fu_996_p1;

assign local_output_42_address0 = zext_ln85_fu_996_p1;

assign local_output_43_address0 = zext_ln85_fu_996_p1;

assign local_output_44_address0 = zext_ln85_fu_996_p1;

assign local_output_45_address0 = zext_ln85_fu_996_p1;

assign local_output_46_address0 = zext_ln85_fu_996_p1;

assign local_output_47_address0 = zext_ln85_fu_996_p1;

assign local_output_48_address0 = zext_ln85_fu_996_p1;

assign local_output_49_address0 = zext_ln85_fu_996_p1;

assign local_output_4_address0 = zext_ln85_fu_996_p1;

assign local_output_50_address0 = zext_ln85_fu_996_p1;

assign local_output_51_address0 = zext_ln85_fu_996_p1;

assign local_output_52_address0 = zext_ln85_fu_996_p1;

assign local_output_53_address0 = zext_ln85_fu_996_p1;

assign local_output_54_address0 = zext_ln85_fu_996_p1;

assign local_output_5_address0 = zext_ln85_fu_996_p1;

assign local_output_6_address0 = zext_ln85_fu_996_p1;

assign local_output_7_address0 = zext_ln85_fu_996_p1;

assign local_output_8_address0 = zext_ln85_fu_996_p1;

assign local_output_9_address0 = zext_ln85_fu_996_p1;

assign local_output_address0 = zext_ln85_fu_996_p1;

assign m_axi_mem1_ARADDR = 64'd0;

assign m_axi_mem1_ARBURST = 2'd0;

assign m_axi_mem1_ARCACHE = 4'd0;

assign m_axi_mem1_ARID = 1'd0;

assign m_axi_mem1_ARLEN = 32'd0;

assign m_axi_mem1_ARLOCK = 2'd0;

assign m_axi_mem1_ARPROT = 3'd0;

assign m_axi_mem1_ARQOS = 4'd0;

assign m_axi_mem1_ARREGION = 4'd0;

assign m_axi_mem1_ARSIZE = 3'd0;

assign m_axi_mem1_ARUSER = 1'd0;

assign m_axi_mem1_ARVALID = 1'b0;

assign m_axi_mem1_AWADDR = 64'd0;

assign m_axi_mem1_AWBURST = 2'd0;

assign m_axi_mem1_AWCACHE = 4'd0;

assign m_axi_mem1_AWID = 1'd0;

assign m_axi_mem1_AWLEN = 32'd0;

assign m_axi_mem1_AWLOCK = 2'd0;

assign m_axi_mem1_AWPROT = 3'd0;

assign m_axi_mem1_AWQOS = 4'd0;

assign m_axi_mem1_AWREGION = 4'd0;

assign m_axi_mem1_AWSIZE = 3'd0;

assign m_axi_mem1_AWUSER = 1'd0;

assign m_axi_mem1_AWVALID = 1'b0;

assign m_axi_mem1_BREADY = 1'b0;

assign m_axi_mem1_RREADY = 1'b0;

assign m_axi_mem1_WDATA = select_ln92_reg_1566;

assign m_axi_mem1_WID = 1'd0;

assign m_axi_mem1_WLAST = 1'b0;

assign m_axi_mem1_WSTRB = 4'd15;

assign m_axi_mem1_WUSER = 1'd0;

assign or_ln93_fu_1225_p2 = (icmp_ln93_fu_1213_p2 | icmp_ln93_1_fu_1219_p2);

assign select_ln85_1_fu_988_p3 = ((icmp_ln87_fu_968_p2[0:0] == 1'b1) ? add_ln85_1_fu_982_p2 : ap_sig_allocacmp_out_r_load);

assign select_ln85_fu_974_p3 = ((icmp_ln87_fu_968_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_out_c_load);

assign select_ln92_fu_1237_p3 = ((and_ln93_fu_1231_p2[0:0] == 1'b1) ? bitcast_ln93_fu_1196_p1 : 32'd0);

assign tmp_2_fu_1199_p4 = {{bitcast_ln93_fu_1196_p1[30:23]}};

assign trunc_ln93_fu_1209_p1 = bitcast_ln93_fu_1196_p1[22:0];

assign zext_ln85_fu_996_p1 = select_ln85_1_fu_988_p3;

endmodule //conv_conv_Pipeline_VITIS_LOOP_85_13_VITIS_LOOP_87_14
