// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv_conv_Pipeline_VITIS_LOOP_36_8_VITIS_LOOP_37_9 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        output_fm_address0,
        output_fm_ce0,
        output_fm_we0,
        output_fm_d0,
        output_fm_q0,
        add_ln42_2,
        select_ln30_2,
        mul_ln42_1,
        mul_ln42_2,
        weights_0_address0,
        weights_0_ce0,
        weights_0_q0,
        weights_1_address0,
        weights_1_ce0,
        weights_1_q0,
        weights_2_address0,
        weights_2_ce0,
        weights_2_q0,
        weights_3_address0,
        weights_3_ce0,
        weights_3_q0,
        weights_4_address0,
        weights_4_ce0,
        weights_4_q0,
        weights_5_address0,
        weights_5_ce0,
        weights_5_q0,
        weights_6_address0,
        weights_6_ce0,
        weights_6_q0,
        weights_7_address0,
        weights_7_ce0,
        weights_7_q0,
        weights_8_address0,
        weights_8_ce0,
        weights_8_q0,
        weights_9_address0,
        weights_9_ce0,
        weights_9_q0,
        weights_10_address0,
        weights_10_ce0,
        weights_10_q0,
        zext_ln32,
        input_fm_0_address0,
        input_fm_0_ce0,
        input_fm_0_q0,
        input_fm_1_address0,
        input_fm_1_ce0,
        input_fm_1_q0,
        input_fm_2_address0,
        input_fm_2_ce0,
        input_fm_2_q0,
        input_fm_3_address0,
        input_fm_3_ce0,
        input_fm_3_q0,
        input_fm_4_address0,
        input_fm_4_ce0,
        input_fm_4_q0,
        input_fm_5_address0,
        input_fm_5_ce0,
        input_fm_5_q0,
        input_fm_6_address0,
        input_fm_6_ce0,
        input_fm_6_q0,
        input_fm_7_address0,
        input_fm_7_ce0,
        input_fm_7_q0,
        input_fm_8_address0,
        input_fm_8_ce0,
        input_fm_8_q0,
        input_fm_9_address0,
        input_fm_9_ce0,
        input_fm_9_q0,
        input_fm_10_address0,
        input_fm_10_ce0,
        input_fm_10_q0,
        grp_fu_1186_p_din0,
        grp_fu_1186_p_din1,
        grp_fu_1186_p_opcode,
        grp_fu_1186_p_dout0,
        grp_fu_1186_p_ce,
        grp_fu_1190_p_din0,
        grp_fu_1190_p_din1,
        grp_fu_1190_p_dout0,
        grp_fu_1190_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [17:0] output_fm_address0;
output   output_fm_ce0;
output   output_fm_we0;
output  [31:0] output_fm_d0;
input  [31:0] output_fm_q0;
input  [17:0] add_ln42_2;
input  [8:0] select_ln30_2;
input  [9:0] mul_ln42_1;
input  [11:0] mul_ln42_2;
output  [11:0] weights_0_address0;
output   weights_0_ce0;
input  [31:0] weights_0_q0;
output  [11:0] weights_1_address0;
output   weights_1_ce0;
input  [31:0] weights_1_q0;
output  [11:0] weights_2_address0;
output   weights_2_ce0;
input  [31:0] weights_2_q0;
output  [11:0] weights_3_address0;
output   weights_3_ce0;
input  [31:0] weights_3_q0;
output  [11:0] weights_4_address0;
output   weights_4_ce0;
input  [31:0] weights_4_q0;
output  [11:0] weights_5_address0;
output   weights_5_ce0;
input  [31:0] weights_5_q0;
output  [11:0] weights_6_address0;
output   weights_6_ce0;
input  [31:0] weights_6_q0;
output  [11:0] weights_7_address0;
output   weights_7_ce0;
input  [31:0] weights_7_q0;
output  [11:0] weights_8_address0;
output   weights_8_ce0;
input  [31:0] weights_8_q0;
output  [11:0] weights_9_address0;
output   weights_9_ce0;
input  [31:0] weights_9_q0;
output  [11:0] weights_10_address0;
output   weights_10_ce0;
input  [31:0] weights_10_q0;
input  [7:0] zext_ln32;
output  [13:0] input_fm_0_address0;
output   input_fm_0_ce0;
input  [31:0] input_fm_0_q0;
output  [13:0] input_fm_1_address0;
output   input_fm_1_ce0;
input  [31:0] input_fm_1_q0;
output  [13:0] input_fm_2_address0;
output   input_fm_2_ce0;
input  [31:0] input_fm_2_q0;
output  [13:0] input_fm_3_address0;
output   input_fm_3_ce0;
input  [31:0] input_fm_3_q0;
output  [13:0] input_fm_4_address0;
output   input_fm_4_ce0;
input  [31:0] input_fm_4_q0;
output  [13:0] input_fm_5_address0;
output   input_fm_5_ce0;
input  [31:0] input_fm_5_q0;
output  [13:0] input_fm_6_address0;
output   input_fm_6_ce0;
input  [31:0] input_fm_6_q0;
output  [13:0] input_fm_7_address0;
output   input_fm_7_ce0;
input  [31:0] input_fm_7_q0;
output  [13:0] input_fm_8_address0;
output   input_fm_8_ce0;
input  [31:0] input_fm_8_q0;
output  [13:0] input_fm_9_address0;
output   input_fm_9_ce0;
input  [31:0] input_fm_9_q0;
output  [13:0] input_fm_10_address0;
output   input_fm_10_ce0;
input  [31:0] input_fm_10_q0;
output  [31:0] grp_fu_1186_p_din0;
output  [31:0] grp_fu_1186_p_din1;
output  [1:0] grp_fu_1186_p_opcode;
input  [31:0] grp_fu_1186_p_dout0;
output   grp_fu_1186_p_ce;
output  [31:0] grp_fu_1190_p_din0;
output  [31:0] grp_fu_1190_p_din1;
input  [31:0] grp_fu_1190_p_dout0;
output   grp_fu_1190_p_ce;

reg ap_idle;
reg[17:0] output_fm_address0;
reg output_fm_ce0;
reg output_fm_we0;
reg weights_0_ce0;
reg weights_1_ce0;
reg weights_2_ce0;
reg weights_3_ce0;
reg weights_4_ce0;
reg weights_5_ce0;
reg weights_6_ce0;
reg weights_7_ce0;
reg weights_8_ce0;
reg weights_9_ce0;
reg weights_10_ce0;
reg input_fm_0_ce0;
reg input_fm_1_ce0;
reg input_fm_2_ce0;
reg input_fm_3_ce0;
reg input_fm_4_ce0;
reg input_fm_5_ce0;
reg input_fm_6_ce0;
reg input_fm_7_ce0;
reg input_fm_8_ce0;
reg input_fm_9_ce0;
reg input_fm_10_ce0;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_state8_pp0_stage7_iter0;
wire    ap_block_state16_pp0_stage7_iter1;
wire    ap_block_pp0_stage7_subdone;
reg   [0:0] icmp_ln36_reg_932;
reg    ap_condition_exit_pp0_iter0_stage7;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state9_pp0_stage0_iter1;
wire    ap_block_state17_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
wire   [10:0] mul_ln42_1_cast_fu_485_p1;
reg   [10:0] mul_ln42_1_cast_reg_917;
reg   [6:0] indvar_flatten32_load_reg_922;
reg   [17:0] output_fm_addr_reg_927;
reg   [17:0] output_fm_addr_reg_927_pp0_iter1_reg;
reg   [17:0] output_fm_addr_reg_927_pp0_iter2_reg;
wire   [0:0] icmp_ln36_fu_507_p2;
reg   [0:0] icmp_ln36_reg_932_pp0_iter1_reg;
wire   [0:0] icmp_ln37_fu_516_p2;
reg   [0:0] icmp_ln37_reg_936;
wire   [3:0] select_ln36_fu_522_p3;
reg   [3:0] select_ln36_reg_943;
reg   [3:0] select_ln36_reg_943_pp0_iter1_reg;
wire   [8:0] add_ln40_fu_540_p2;
reg   [8:0] add_ln40_reg_949;
wire   [7:0] trunc_ln41_fu_546_p1;
reg   [7:0] trunc_ln41_reg_955;
reg   [3:0] j_3_reg_960;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state10_pp0_stage1_iter1;
wire    ap_block_state18_pp0_stage1_iter2;
wire    ap_block_pp0_stage1_11001;
wire   [6:0] add_ln36_5_fu_570_p2;
reg   [6:0] add_ln36_5_reg_965;
wire   [3:0] add_ln36_fu_575_p2;
reg   [3:0] add_ln36_reg_970;
wire   [10:0] add_ln42_fu_601_p2;
reg  signed [10:0] add_ln42_reg_975;
wire   [0:0] and_ln41_fu_632_p2;
reg   [0:0] and_ln41_reg_980;
reg   [0:0] and_ln41_reg_980_pp0_iter1_reg;
reg   [0:0] and_ln41_reg_980_pp0_iter2_reg;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state11_pp0_stage2_iter1;
wire    ap_block_state19_pp0_stage2_iter2;
wire    ap_block_pp0_stage2_11001;
wire  signed [13:0] grp_fu_879_p2;
reg  signed [13:0] mul_ln42_4_reg_994;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state6_pp0_stage5_iter0;
wire    ap_block_state14_pp0_stage5_iter1;
wire    ap_block_state22_pp0_stage5_iter2;
wire    ap_block_pp0_stage5_11001;
reg   [4:0] tmp_12_reg_999;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_state7_pp0_stage6_iter0;
wire    ap_block_state15_pp0_stage6_iter1;
wire    ap_block_state23_pp0_stage6_iter2;
wire    ap_block_pp0_stage6_11001;
wire   [3:0] select_ln36_14_fu_688_p3;
reg   [3:0] select_ln36_14_reg_1059;
wire    ap_block_pp0_stage7_11001;
reg   [31:0] input_fm_0_load_reg_1064;
reg   [31:0] input_fm_1_load_reg_1069;
reg   [31:0] input_fm_2_load_reg_1074;
reg   [31:0] input_fm_3_load_reg_1079;
reg   [31:0] input_fm_4_load_reg_1084;
reg   [31:0] input_fm_5_load_reg_1089;
reg   [31:0] input_fm_6_load_reg_1094;
reg   [31:0] input_fm_7_load_reg_1099;
reg   [31:0] input_fm_8_load_reg_1104;
reg   [31:0] input_fm_9_load_reg_1109;
reg   [31:0] input_fm_10_load_reg_1114;
wire   [31:0] tmp_fu_779_p13;
reg   [31:0] tmp_reg_1174;
wire   [31:0] tmp_1_fu_843_p13;
reg   [31:0] tmp_1_reg_1179;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_state13_pp0_stage4_iter1;
wire    ap_block_state21_pp0_stage4_iter2;
wire    ap_block_pp0_stage4_11001;
reg   [31:0] mul_reg_1184;
reg   [31:0] output_fm_load_reg_1189;
wire   [31:0] bitcast_ln42_11_fu_871_p1;
reg   [31:0] add_reg_1199;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage6_subdone;
wire   [63:0] add_ln42_2_cast_fu_480_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln42_15_fu_673_p1;
wire    ap_block_pp0_stage6;
wire   [63:0] zext_ln42_fu_720_p1;
wire    ap_block_pp0_stage1;
reg   [3:0] k_fu_128;
wire   [3:0] add_ln37_fu_693_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_k_load;
reg   [3:0] j_fu_132;
reg   [6:0] indvar_flatten32_fu_136;
reg   [6:0] ap_sig_allocacmp_indvar_flatten32_load;
wire    ap_block_pp0_stage7;
wire    ap_block_pp0_stage5;
wire   [3:0] add_ln40_3_fu_530_p2;
wire  signed [8:0] sext_ln40_fu_536_p1;
wire   [8:0] zext_ln32_cast_fu_476_p1;
wire   [8:0] zext_ln36_1_fu_553_p1;
wire   [8:0] empty_fu_557_p2;
wire   [8:0] zext_ln36_fu_581_p1;
wire   [8:0] p_mid1_fu_585_p2;
wire   [8:0] select_ln36_1_fu_590_p3;
wire  signed [10:0] sext_ln42_fu_597_p1;
wire   [0:0] tmp_11_fu_606_p3;
wire   [0:0] tmp_10_fu_562_p3;
wire   [0:0] select_ln36_13_fu_614_p3;
wire   [0:0] icmp_ln41_fu_627_p2;
wire   [0:0] xor_ln36_fu_621_p2;
wire   [4:0] grp_fu_638_p1;
wire   [8:0] grp_fu_646_p0;
wire   [65:0] grp_fu_646_p1;
wire    ap_block_pp0_stage2;
wire   [72:0] grp_fu_646_p2;
wire   [13:0] zext_ln42_14_fu_665_p1;
(* use_dsp48 = "no" *) wire   [13:0] add_ln42_6_fu_668_p2;
wire   [11:0] zext_ln36_8_fu_712_p1;
wire   [11:0] add_ln36_7_fu_715_p2;
wire   [31:0] tmp_fu_779_p1;
wire   [31:0] tmp_fu_779_p2;
wire   [31:0] tmp_fu_779_p3;
wire   [31:0] tmp_fu_779_p4;
wire   [31:0] tmp_fu_779_p5;
wire   [31:0] tmp_fu_779_p6;
wire   [31:0] tmp_fu_779_p7;
wire   [31:0] tmp_fu_779_p8;
wire   [31:0] tmp_fu_779_p9;
wire   [31:0] tmp_fu_779_p10;
wire   [31:0] tmp_fu_779_p11;
wire   [3:0] grp_fu_638_p2;
wire    ap_block_pp0_stage4;
wire   [31:0] tmp_1_fu_843_p1;
wire   [31:0] tmp_1_fu_843_p2;
wire   [31:0] tmp_1_fu_843_p3;
wire   [31:0] tmp_1_fu_843_p4;
wire   [31:0] tmp_1_fu_843_p5;
wire   [31:0] tmp_1_fu_843_p6;
wire   [31:0] tmp_1_fu_843_p7;
wire   [31:0] tmp_1_fu_843_p8;
wire   [31:0] tmp_1_fu_843_p9;
wire   [31:0] tmp_1_fu_843_p10;
wire   [31:0] tmp_1_fu_843_p11;
wire   [3:0] tmp_1_fu_843_p12;
wire   [4:0] grp_fu_879_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage6;
reg    ap_idle_pp0_0to0;
reg   [7:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to2;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state12_pp0_stage3_iter1;
wire    ap_block_state20_pp0_stage3_iter2;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_block_pp0_stage1_00001;
wire   [72:0] grp_fu_646_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

conv_urem_8ns_5ns_4_12_1 #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 4 ))
urem_8ns_5ns_4_12_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln41_reg_955),
    .din1(grp_fu_638_p1),
    .ce(1'b1),
    .dout(grp_fu_638_p2)
);

conv_mul_9ns_66ns_73_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 66 ),
    .dout_WIDTH( 73 ))
mul_9ns_66ns_73_5_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_646_p0),
    .din1(grp_fu_646_p1),
    .ce(1'b1),
    .dout(grp_fu_646_p2)
);

conv_mux_114_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_114_32_1_1_U11(
    .din0(tmp_fu_779_p1),
    .din1(tmp_fu_779_p2),
    .din2(tmp_fu_779_p3),
    .din3(tmp_fu_779_p4),
    .din4(tmp_fu_779_p5),
    .din5(tmp_fu_779_p6),
    .din6(tmp_fu_779_p7),
    .din7(tmp_fu_779_p8),
    .din8(tmp_fu_779_p9),
    .din9(tmp_fu_779_p10),
    .din10(tmp_fu_779_p11),
    .din11(select_ln36_reg_943_pp0_iter1_reg),
    .dout(tmp_fu_779_p13)
);

conv_mux_114_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_114_32_1_1_U12(
    .din0(tmp_1_fu_843_p1),
    .din1(tmp_1_fu_843_p2),
    .din2(tmp_1_fu_843_p3),
    .din3(tmp_1_fu_843_p4),
    .din4(tmp_1_fu_843_p5),
    .din5(tmp_1_fu_843_p6),
    .din6(tmp_1_fu_843_p7),
    .din7(tmp_1_fu_843_p8),
    .din8(tmp_1_fu_843_p9),
    .din9(tmp_1_fu_843_p10),
    .din10(tmp_1_fu_843_p11),
    .din11(tmp_1_fu_843_p12),
    .dout(tmp_1_fu_843_p13)
);

conv_mul_mul_11s_5ns_14_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 14 ))
mul_mul_11s_5ns_14_4_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln42_reg_975),
    .din1(grp_fu_879_p1),
    .ce(1'b1),
    .dout(grp_fu_879_p2)
);

conv_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage7),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_subdone) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage7)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage6_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage6))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten32_fu_136 <= 7'd0;
    end else if (((icmp_ln36_reg_932 == 1'd0) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        indvar_flatten32_fu_136 <= add_ln36_5_reg_965;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_fu_132 <= 4'd0;
    end else if (((icmp_ln36_reg_932 == 1'd0) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        j_fu_132 <= select_ln36_14_fu_688_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_fu_128 <= 4'd0;
    end else if (((icmp_ln36_reg_932 == 1'd0) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        k_fu_128 <= add_ln37_fu_693_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln36_5_reg_965 <= add_ln36_5_fu_570_p2;
        and_ln41_reg_980_pp0_iter1_reg <= and_ln41_reg_980;
        and_ln41_reg_980_pp0_iter2_reg <= and_ln41_reg_980_pp0_iter1_reg;
        j_3_reg_960 <= j_fu_132;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln36_reg_932 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln36_reg_970 <= add_ln36_fu_575_p2;
        add_ln42_reg_975 <= add_ln42_fu_601_p2;
        and_ln41_reg_980 <= and_ln41_fu_632_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln36_fu_507_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln40_reg_949 <= add_ln40_fu_540_p2;
        icmp_ln37_reg_936 <= icmp_ln37_fu_516_p2;
        select_ln36_reg_943 <= select_ln36_fu_522_p3;
        trunc_ln41_reg_955 <= trunc_ln41_fu_546_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln41_reg_980_pp0_iter2_reg) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        add_reg_1199 <= grp_fu_1186_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln36_reg_932 <= icmp_ln36_fu_507_p2;
        icmp_ln36_reg_932_pp0_iter1_reg <= icmp_ln36_reg_932;
        indvar_flatten32_load_reg_922 <= ap_sig_allocacmp_indvar_flatten32_load;
        mul_ln42_1_cast_reg_917[9 : 0] <= mul_ln42_1_cast_fu_485_p1[9 : 0];
        output_fm_addr_reg_927 <= add_ln42_2_cast_fu_480_p1;
        output_fm_addr_reg_927_pp0_iter1_reg <= output_fm_addr_reg_927;
        output_fm_addr_reg_927_pp0_iter2_reg <= output_fm_addr_reg_927_pp0_iter1_reg;
        select_ln36_reg_943_pp0_iter1_reg <= select_ln36_reg_943;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln41_reg_980) & (icmp_ln36_reg_932 == 1'd0) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        input_fm_0_load_reg_1064 <= input_fm_0_q0;
        input_fm_10_load_reg_1114 <= input_fm_10_q0;
        input_fm_1_load_reg_1069 <= input_fm_1_q0;
        input_fm_2_load_reg_1074 <= input_fm_2_q0;
        input_fm_3_load_reg_1079 <= input_fm_3_q0;
        input_fm_4_load_reg_1084 <= input_fm_4_q0;
        input_fm_5_load_reg_1089 <= input_fm_5_q0;
        input_fm_6_load_reg_1094 <= input_fm_6_q0;
        input_fm_7_load_reg_1099 <= input_fm_7_q0;
        input_fm_8_load_reg_1104 <= input_fm_8_q0;
        input_fm_9_load_reg_1109 <= input_fm_9_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln36_reg_932 == 1'd0) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        mul_ln42_4_reg_994 <= grp_fu_879_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln41_reg_980_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_reg_1184 <= grp_fu_1190_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln41_reg_980_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_fm_load_reg_1189 <= output_fm_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln36_reg_932 == 1'd0) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        select_ln36_14_reg_1059 <= select_ln36_14_fu_688_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln41_reg_980) & (icmp_ln36_reg_932 == 1'd0) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        tmp_12_reg_999 <= {{grp_fu_646_p2[72:68]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln41_reg_980_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        tmp_1_reg_1179 <= tmp_1_fu_843_p13;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln41_reg_980_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_reg_1174 <= tmp_fu_779_p13;
    end
end

always @ (*) begin
    if (((icmp_ln36_reg_932 == 1'd1) & (1'b0 == ap_block_pp0_stage7_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln36_reg_932_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        ap_condition_exit_pp0_iter1_stage6 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage6 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_subdone) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage7_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten32_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten32_load = indvar_flatten32_fu_136;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_k_load = 4'd0;
    end else begin
        ap_sig_allocacmp_k_load = k_fu_128;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        input_fm_0_ce0 = 1'b1;
    end else begin
        input_fm_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        input_fm_10_ce0 = 1'b1;
    end else begin
        input_fm_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        input_fm_1_ce0 = 1'b1;
    end else begin
        input_fm_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        input_fm_2_ce0 = 1'b1;
    end else begin
        input_fm_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        input_fm_3_ce0 = 1'b1;
    end else begin
        input_fm_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        input_fm_4_ce0 = 1'b1;
    end else begin
        input_fm_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        input_fm_5_ce0 = 1'b1;
    end else begin
        input_fm_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        input_fm_6_ce0 = 1'b1;
    end else begin
        input_fm_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        input_fm_7_ce0 = 1'b1;
    end else begin
        input_fm_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        input_fm_8_ce0 = 1'b1;
    end else begin
        input_fm_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        input_fm_9_ce0 = 1'b1;
    end else begin
        input_fm_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        output_fm_address0 = output_fm_addr_reg_927_pp0_iter2_reg;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        output_fm_address0 = output_fm_addr_reg_927_pp0_iter1_reg;
    end else begin
        output_fm_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)))) begin
        output_fm_ce0 = 1'b1;
    end else begin
        output_fm_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln41_reg_980_pp0_iter2_reg) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        output_fm_we0 = 1'b1;
    end else begin
        output_fm_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        weights_0_ce0 = 1'b1;
    end else begin
        weights_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        weights_10_ce0 = 1'b1;
    end else begin
        weights_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        weights_1_ce0 = 1'b1;
    end else begin
        weights_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        weights_2_ce0 = 1'b1;
    end else begin
        weights_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        weights_3_ce0 = 1'b1;
    end else begin
        weights_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        weights_4_ce0 = 1'b1;
    end else begin
        weights_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        weights_5_ce0 = 1'b1;
    end else begin
        weights_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        weights_6_ce0 = 1'b1;
    end else begin
        weights_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        weights_7_ce0 = 1'b1;
    end else begin
        weights_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        weights_8_ce0 = 1'b1;
    end else begin
        weights_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        weights_9_ce0 = 1'b1;
    end else begin
        weights_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage6))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln36_5_fu_570_p2 = (indvar_flatten32_load_reg_922 + 7'd1);

assign add_ln36_7_fu_715_p2 = (mul_ln42_2 + zext_ln36_8_fu_712_p1);

assign add_ln36_fu_575_p2 = (j_fu_132 + 4'd1);

assign add_ln37_fu_693_p2 = (select_ln36_reg_943 + 4'd1);

assign add_ln40_3_fu_530_p2 = ($signed(select_ln36_fu_522_p3) + $signed(4'd11));

assign add_ln40_fu_540_p2 = ($signed(sext_ln40_fu_536_p1) + $signed(zext_ln32_cast_fu_476_p1));

assign add_ln42_2_cast_fu_480_p1 = add_ln42_2;

assign add_ln42_6_fu_668_p2 = ($signed(mul_ln42_4_reg_994) + $signed(zext_ln42_14_fu_665_p1));

assign add_ln42_fu_601_p2 = ($signed(mul_ln42_1_cast_reg_917) + $signed(sext_ln42_fu_597_p1));

assign and_ln41_fu_632_p2 = (xor_ln36_fu_621_p2 & icmp_ln41_fu_627_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage5_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage6_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage7_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage4_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage5_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage6_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage7_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage7;

assign bitcast_ln42_11_fu_871_p1 = output_fm_load_reg_1189;

assign empty_fu_557_p2 = (zext_ln36_1_fu_553_p1 + select_ln30_2);

assign grp_fu_1186_p_ce = 1'b1;

assign grp_fu_1186_p_din0 = bitcast_ln42_11_fu_871_p1;

assign grp_fu_1186_p_din1 = mul_reg_1184;

assign grp_fu_1186_p_opcode = 2'd0;

assign grp_fu_1190_p_ce = 1'b1;

assign grp_fu_1190_p_din0 = tmp_reg_1174;

assign grp_fu_1190_p_din1 = tmp_1_reg_1179;

assign grp_fu_638_p1 = 8'd11;

assign grp_fu_646_p0 = grp_fu_646_p00;

assign grp_fu_646_p00 = add_ln40_reg_949;

assign grp_fu_646_p1 = 73'd26831627743577529624;

assign grp_fu_879_p1 = 14'd21;

assign icmp_ln36_fu_507_p2 = ((ap_sig_allocacmp_indvar_flatten32_load == 7'd121) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_516_p2 = ((ap_sig_allocacmp_k_load == 4'd11) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_627_p2 = ((add_ln40_reg_949 < 9'd226) ? 1'b1 : 1'b0);

assign input_fm_0_address0 = zext_ln42_15_fu_673_p1;

assign input_fm_10_address0 = zext_ln42_15_fu_673_p1;

assign input_fm_1_address0 = zext_ln42_15_fu_673_p1;

assign input_fm_2_address0 = zext_ln42_15_fu_673_p1;

assign input_fm_3_address0 = zext_ln42_15_fu_673_p1;

assign input_fm_4_address0 = zext_ln42_15_fu_673_p1;

assign input_fm_5_address0 = zext_ln42_15_fu_673_p1;

assign input_fm_6_address0 = zext_ln42_15_fu_673_p1;

assign input_fm_7_address0 = zext_ln42_15_fu_673_p1;

assign input_fm_8_address0 = zext_ln42_15_fu_673_p1;

assign input_fm_9_address0 = zext_ln42_15_fu_673_p1;

assign mul_ln42_1_cast_fu_485_p1 = mul_ln42_1;

assign output_fm_d0 = add_reg_1199;

assign p_mid1_fu_585_p2 = (zext_ln36_fu_581_p1 + select_ln30_2);

assign select_ln36_13_fu_614_p3 = ((icmp_ln37_reg_936[0:0] == 1'b1) ? tmp_11_fu_606_p3 : tmp_10_fu_562_p3);

assign select_ln36_14_fu_688_p3 = ((icmp_ln37_reg_936[0:0] == 1'b1) ? add_ln36_reg_970 : j_3_reg_960);

assign select_ln36_1_fu_590_p3 = ((icmp_ln37_reg_936[0:0] == 1'b1) ? p_mid1_fu_585_p2 : empty_fu_557_p2);

assign select_ln36_fu_522_p3 = ((icmp_ln37_fu_516_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_k_load);

assign sext_ln40_fu_536_p1 = $signed(add_ln40_3_fu_530_p2);

assign sext_ln42_fu_597_p1 = $signed(select_ln36_1_fu_590_p3);

assign tmp_10_fu_562_p3 = empty_fu_557_p2[32'd8];

assign tmp_11_fu_606_p3 = p_mid1_fu_585_p2[32'd8];

assign tmp_1_fu_843_p1 = input_fm_0_load_reg_1064;

assign tmp_1_fu_843_p10 = input_fm_9_load_reg_1109;

assign tmp_1_fu_843_p11 = input_fm_10_load_reg_1114;

assign tmp_1_fu_843_p12 = grp_fu_638_p2[3:0];

assign tmp_1_fu_843_p2 = input_fm_1_load_reg_1069;

assign tmp_1_fu_843_p3 = input_fm_2_load_reg_1074;

assign tmp_1_fu_843_p4 = input_fm_3_load_reg_1079;

assign tmp_1_fu_843_p5 = input_fm_4_load_reg_1084;

assign tmp_1_fu_843_p6 = input_fm_5_load_reg_1089;

assign tmp_1_fu_843_p7 = input_fm_6_load_reg_1094;

assign tmp_1_fu_843_p8 = input_fm_7_load_reg_1099;

assign tmp_1_fu_843_p9 = input_fm_8_load_reg_1104;

assign tmp_fu_779_p1 = weights_0_q0;

assign tmp_fu_779_p10 = weights_9_q0;

assign tmp_fu_779_p11 = weights_10_q0;

assign tmp_fu_779_p2 = weights_1_q0;

assign tmp_fu_779_p3 = weights_2_q0;

assign tmp_fu_779_p4 = weights_3_q0;

assign tmp_fu_779_p5 = weights_4_q0;

assign tmp_fu_779_p6 = weights_5_q0;

assign tmp_fu_779_p7 = weights_6_q0;

assign tmp_fu_779_p8 = weights_7_q0;

assign tmp_fu_779_p9 = weights_8_q0;

assign trunc_ln41_fu_546_p1 = add_ln40_fu_540_p2[7:0];

assign weights_0_address0 = zext_ln42_fu_720_p1;

assign weights_10_address0 = zext_ln42_fu_720_p1;

assign weights_1_address0 = zext_ln42_fu_720_p1;

assign weights_2_address0 = zext_ln42_fu_720_p1;

assign weights_3_address0 = zext_ln42_fu_720_p1;

assign weights_4_address0 = zext_ln42_fu_720_p1;

assign weights_5_address0 = zext_ln42_fu_720_p1;

assign weights_6_address0 = zext_ln42_fu_720_p1;

assign weights_7_address0 = zext_ln42_fu_720_p1;

assign weights_8_address0 = zext_ln42_fu_720_p1;

assign weights_9_address0 = zext_ln42_fu_720_p1;

assign xor_ln36_fu_621_p2 = (select_ln36_13_fu_614_p3 ^ 1'd1);

assign zext_ln32_cast_fu_476_p1 = zext_ln32;

assign zext_ln36_1_fu_553_p1 = j_fu_132;

assign zext_ln36_8_fu_712_p1 = select_ln36_14_reg_1059;

assign zext_ln36_fu_581_p1 = add_ln36_fu_575_p2;

assign zext_ln42_14_fu_665_p1 = tmp_12_reg_999;

assign zext_ln42_15_fu_673_p1 = add_ln42_6_fu_668_p2;

assign zext_ln42_fu_720_p1 = add_ln36_7_fu_715_p2;

always @ (posedge ap_clk) begin
    mul_ln42_1_cast_reg_917[10] <= 1'b0;
end

endmodule //conv_conv_Pipeline_VITIS_LOOP_36_8_VITIS_LOOP_37_9
