-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv_conv_Pipeline_VITIS_LOOP_61_10_VITIS_LOOP_62_11_VITIS_LOOP_63_12 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    output_fm_address0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    output_fm_ce0 : OUT STD_LOGIC;
    output_fm_we0 : OUT STD_LOGIC;
    output_fm_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_fm_address1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    output_fm_ce1 : OUT STD_LOGIC;
    output_fm_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of conv_conv_Pipeline_VITIS_LOOP_61_10_VITIS_LOOP_62_11_VITIS_LOOP_63_12 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv18_2F440 : STD_LOGIC_VECTOR (17 downto 0) := "101111010001000000";
    constant ap_const_lv18_1 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000001";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv12_BD1 : STD_LOGIC_VECTOR (11 downto 0) := "101111010001";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv13_37 : STD_LOGIC_VECTOR (12 downto 0) := "0000000110111";
    constant ap_const_lv6_37 : STD_LOGIC_VECTOR (5 downto 0) := "110111";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv18_37 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000110111";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln61_fu_146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln62_fu_167_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln62_reg_393 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln61_1_fu_173_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln61_1_reg_400 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln62_fu_260_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln62_reg_405 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln62_reg_405_pp0_iter3_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal output_fm_addr_reg_415 : STD_LOGIC_VECTOR (17 downto 0);
    signal output_fm_addr_reg_415_pp0_iter6_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal output_fm_addr_reg_415_pp0_iter7_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal output_fm_addr_reg_415_pp0_iter8_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal output_fm_load_reg_421 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln64_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_reg_426 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_reg_426_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_1_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_1_reg_431 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_1_reg_431_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln64_fu_337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln64_reg_441 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln64_3_fu_299_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal z_fu_72 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln63_fu_280_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal y_fu_76 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln62_1_fu_268_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten74_fu_80 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln62_2_fu_187_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal x_fu_84 : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten88_fu_88 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln61_1_fu_152_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_110_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln61_fu_161_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln62_1_fu_181_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln64_fu_226_p0 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln64_fu_226_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln63_fu_237_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln61_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln61_fu_216_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal and_ln61_fu_243_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln62_fu_255_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln62_fu_249_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_343_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_fu_303_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln64_fu_313_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln64_fu_333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_110_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln64_fu_226_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_343_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_343_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_343_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal grp_fu_343_p10 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_343_p30 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln64_fu_226_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component conv_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component conv_mul_7ns_7ns_13_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;


    component conv_ama_addmuladd_13ns_6ns_6ns_6ns_18_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (12 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        din2 : IN STD_LOGIC_VECTOR (5 downto 0);
        din3 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component conv_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    fcmp_32ns_32ns_1_2_no_dsp_1_U75 : component conv_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_110_p0,
        din1 => ap_const_lv32_0,
        ce => ap_const_logic_1,
        opcode => ap_const_lv5_4,
        dout => grp_fu_110_p2);

    mul_7ns_7ns_13_1_1_U76 : component conv_mul_7ns_7ns_13_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 7,
        din1_WIDTH => 7,
        dout_WIDTH => 13)
    port map (
        din0 => mul_ln64_fu_226_p0,
        din1 => mul_ln64_fu_226_p1,
        dout => mul_ln64_fu_226_p2);

    ama_addmuladd_13ns_6ns_6ns_6ns_18_4_1_U77 : component conv_ama_addmuladd_13ns_6ns_6ns_6ns_18_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 13,
        din1_WIDTH => 6,
        din2_WIDTH => 6,
        din3_WIDTH => 6,
        dout_WIDTH => 18)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => mul_ln64_fu_226_p2,
        din1 => grp_fu_343_p1,
        din2 => grp_fu_343_p2,
        din3 => grp_fu_343_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_343_p4);

    flow_control_loop_pipe_sequential_init_U : component conv_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten74_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten74_fu_80 <= ap_const_lv12_0;
                elsif (((icmp_ln61_fu_146_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten74_fu_80 <= select_ln62_2_fu_187_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten88_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten88_fu_88 <= ap_const_lv18_0;
                elsif (((icmp_ln61_fu_146_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten88_fu_88 <= add_ln61_1_fu_152_p2;
                end if;
            end if; 
        end if;
    end process;

    x_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_84 <= ap_const_lv7_0;
                elsif (((icmp_ln61_fu_146_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    x_fu_84 <= select_ln61_1_fu_173_p3;
                end if;
            end if; 
        end if;
    end process;

    y_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    y_fu_76 <= ap_const_lv6_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    y_fu_76 <= select_ln62_1_fu_268_p3;
                end if;
            end if; 
        end if;
    end process;

    z_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    z_fu_72 <= ap_const_lv6_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    z_fu_72 <= add_ln63_fu_280_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                and_ln64_reg_441 <= and_ln64_fu_337_p2;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                icmp_ln64_1_reg_431 <= icmp_ln64_1_fu_323_p2;
                icmp_ln64_1_reg_431_pp0_iter7_reg <= icmp_ln64_1_reg_431;
                icmp_ln64_reg_426 <= icmp_ln64_fu_317_p2;
                icmp_ln64_reg_426_pp0_iter7_reg <= icmp_ln64_reg_426;
                output_fm_addr_reg_415 <= zext_ln64_3_fu_299_p1(18 - 1 downto 0);
                output_fm_addr_reg_415_pp0_iter6_reg <= output_fm_addr_reg_415;
                output_fm_addr_reg_415_pp0_iter7_reg <= output_fm_addr_reg_415_pp0_iter6_reg;
                output_fm_addr_reg_415_pp0_iter8_reg <= output_fm_addr_reg_415_pp0_iter7_reg;
                select_ln62_reg_405 <= select_ln62_fu_260_p3;
                select_ln62_reg_405_pp0_iter3_reg <= select_ln62_reg_405;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln61_fu_146_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln62_reg_393 <= icmp_ln62_fu_167_p2;
                select_ln61_1_reg_400 <= select_ln61_1_fu_173_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then
                output_fm_load_reg_421 <= output_fm_q1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln61_1_fu_152_p2 <= std_logic_vector(unsigned(indvar_flatten88_fu_88) + unsigned(ap_const_lv18_1));
    add_ln61_fu_161_p2 <= std_logic_vector(unsigned(x_fu_84) + unsigned(ap_const_lv7_1));
    add_ln62_1_fu_181_p2 <= std_logic_vector(unsigned(indvar_flatten74_fu_80) + unsigned(ap_const_lv12_1));
    add_ln62_fu_249_p2 <= std_logic_vector(unsigned(select_ln61_fu_216_p3) + unsigned(ap_const_lv6_1));
    add_ln63_fu_280_p2 <= std_logic_vector(unsigned(select_ln62_fu_260_p3) + unsigned(ap_const_lv6_1));
    and_ln61_fu_243_p2 <= (xor_ln61_fu_232_p2 and icmp_ln63_fu_237_p2);
    and_ln64_fu_337_p2 <= (or_ln64_fu_333_p2 and grp_fu_110_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln61_fu_146_p2)
    begin
        if (((icmp_ln61_fu_146_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter8_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_110_p0 <= output_fm_load_reg_421;
    grp_fu_343_p1 <= grp_fu_343_p10(6 - 1 downto 0);
    grp_fu_343_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln62_1_fu_268_p3),13));
    grp_fu_343_p2 <= ap_const_lv18_37(6 - 1 downto 0);
    grp_fu_343_p3 <= grp_fu_343_p30(6 - 1 downto 0);
    grp_fu_343_p30 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln62_reg_405_pp0_iter3_reg),18));
    icmp_ln61_fu_146_p2 <= "1" when (indvar_flatten88_fu_88 = ap_const_lv18_2F440) else "0";
    icmp_ln62_fu_167_p2 <= "1" when (indvar_flatten74_fu_80 = ap_const_lv12_BD1) else "0";
    icmp_ln63_fu_237_p2 <= "1" when (z_fu_72 = ap_const_lv6_37) else "0";
    icmp_ln64_1_fu_323_p2 <= "1" when (trunc_ln64_fu_313_p1 = ap_const_lv23_0) else "0";
    icmp_ln64_fu_317_p2 <= "0" when (tmp_fu_303_p4 = ap_const_lv8_FF) else "1";
    mul_ln64_fu_226_p0 <= mul_ln64_fu_226_p00(7 - 1 downto 0);
    mul_ln64_fu_226_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln61_1_reg_400),13));
    mul_ln64_fu_226_p1 <= ap_const_lv13_37(7 - 1 downto 0);
    or_ln62_fu_255_p2 <= (icmp_ln62_reg_393 or and_ln61_fu_243_p2);
    or_ln64_fu_333_p2 <= (icmp_ln64_reg_426_pp0_iter7_reg or icmp_ln64_1_reg_431_pp0_iter7_reg);
    output_fm_address0 <= output_fm_addr_reg_415_pp0_iter8_reg;
    output_fm_address1 <= zext_ln64_3_fu_299_p1(18 - 1 downto 0);

    output_fm_ce0_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            output_fm_ce0 <= ap_const_logic_1;
        else 
            output_fm_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    output_fm_ce1_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            output_fm_ce1 <= ap_const_logic_1;
        else 
            output_fm_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    output_fm_d0 <= ap_const_lv32_0;

    output_fm_we0_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001, and_ln64_reg_441)
    begin
        if (((ap_const_lv1_1 = and_ln64_reg_441) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            output_fm_we0 <= ap_const_logic_1;
        else 
            output_fm_we0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln61_1_fu_173_p3 <= 
        add_ln61_fu_161_p2 when (icmp_ln62_fu_167_p2(0) = '1') else 
        x_fu_84;
    select_ln61_fu_216_p3 <= 
        ap_const_lv6_0 when (icmp_ln62_reg_393(0) = '1') else 
        y_fu_76;
    select_ln62_1_fu_268_p3 <= 
        add_ln62_fu_249_p2 when (and_ln61_fu_243_p2(0) = '1') else 
        select_ln61_fu_216_p3;
    select_ln62_2_fu_187_p3 <= 
        ap_const_lv12_1 when (icmp_ln62_fu_167_p2(0) = '1') else 
        add_ln62_1_fu_181_p2;
    select_ln62_fu_260_p3 <= 
        ap_const_lv6_0 when (or_ln62_fu_255_p2(0) = '1') else 
        z_fu_72;
    tmp_fu_303_p4 <= output_fm_q1(30 downto 23);
    trunc_ln64_fu_313_p1 <= output_fm_q1(23 - 1 downto 0);
    xor_ln61_fu_232_p2 <= (icmp_ln62_reg_393 xor ap_const_lv1_1);
    zext_ln64_3_fu_299_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_343_p4),64));
end behav;
