// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv_conv_Pipeline_VITIS_LOOP_27_4_VITIS_LOOP_29_6_VITIS_LOOP_35_8_VITIS_LOOP_36_9 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        output_fm_address0,
        output_fm_ce0,
        output_fm_we0,
        output_fm_d0,
        output_fm_q0,
        weights_address0,
        weights_ce0,
        weights_q0,
        input_fm_address0,
        input_fm_ce0,
        input_fm_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [17:0] output_fm_address0;
output   output_fm_ce0;
output   output_fm_we0;
output  [31:0] output_fm_d0;
input  [31:0] output_fm_q0;
output  [14:0] weights_address0;
output   weights_ce0;
input  [31:0] weights_q0;
output  [17:0] input_fm_address0;
output   input_fm_ce0;
input  [31:0] input_fm_q0;

reg ap_idle;
reg[17:0] output_fm_address0;
reg output_fm_ce0;
reg output_fm_we0;
reg weights_ce0;
reg input_fm_ce0;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_state8_pp0_stage7_iter0;
wire    ap_block_state16_pp0_stage7_iter1;
wire    ap_block_pp0_stage7_subdone;
reg   [0:0] icmp_ln27_reg_1209;
reg    ap_condition_exit_pp0_iter0_stage7;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [12:0] indvar_flatten50_load_reg_1194;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state10_pp0_stage1_iter1;
wire    ap_block_state18_pp0_stage1_iter2;
wire    ap_block_pp0_stage1_11001;
reg   [18:0] indvar_flatten95_load_reg_1199;
reg   [20:0] indvar_flatten153_load_reg_1204;
wire   [0:0] icmp_ln27_fu_283_p2;
reg   [0:0] icmp_ln27_reg_1209_pp0_iter1_reg;
wire   [26:0] add_ln27_1_fu_289_p2;
reg   [26:0] add_ln27_1_reg_1213;
reg   [6:0] f_load_reg_1218;
wire   [6:0] add_ln27_fu_301_p2;
reg   [6:0] add_ln27_reg_1223;
wire   [0:0] icmp_ln28_fu_307_p2;
reg   [0:0] icmp_ln28_reg_1228;
wire   [0:0] xor_ln27_fu_321_p2;
reg   [0:0] xor_ln27_reg_1238;
wire   [0:0] icmp_ln31_fu_327_p2;
reg   [0:0] icmp_ln31_reg_1246;
wire   [0:0] icmp_ln29_fu_333_p2;
reg   [0:0] icmp_ln29_reg_1251;
wire   [0:0] and_ln27_4_fu_339_p2;
reg   [0:0] and_ln27_4_reg_1256;
wire   [1:0] select_ln28_1_fu_351_p3;
reg   [1:0] select_ln28_1_reg_1262;
reg   [7:0] indvar_flatten21_load_reg_1273;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state11_pp0_stage2_iter1;
wire    ap_block_state19_pp0_stage2_iter2;
wire    ap_block_pp0_stage2_11001;
wire   [8:0] empty_fu_421_p2;
reg   [8:0] empty_reg_1278;
wire   [0:0] rev_fu_435_p2;
reg   [0:0] rev_reg_1283;
wire   [6:0] select_ln27_1_fu_444_p3;
reg   [6:0] select_ln27_1_reg_1288;
wire   [0:0] or_ln28_fu_497_p2;
reg   [0:0] or_ln28_reg_1293;
wire   [7:0] select_ln28_fu_501_p3;
reg   [7:0] select_ln28_reg_1299;
wire   [0:0] or_ln28_1_fu_535_p2;
reg   [0:0] or_ln28_1_reg_1309;
wire   [0:0] and_ln28_3_fu_556_p2;
reg   [0:0] and_ln28_3_reg_1314;
wire   [7:0] add_ln29_fu_562_p2;
reg   [7:0] add_ln29_reg_1321;
wire   [0:0] or_ln29_1_fu_573_p2;
reg   [0:0] or_ln29_1_reg_1327;
wire   [7:0] select_ln29_fu_578_p3;
reg   [7:0] select_ln29_reg_1332;
wire   [5:0] select_ln29_2_fu_596_p3;
reg   [5:0] select_ln29_2_reg_1337;
wire   [0:0] and_ln29_1_fu_624_p2;
reg   [0:0] and_ln29_1_reg_1342;
wire   [7:0] add_ln31_fu_630_p2;
reg   [7:0] add_ln31_reg_1349;
wire   [0:0] or_ln31_1_fu_642_p2;
reg   [0:0] or_ln31_1_reg_1354;
wire   [3:0] select_ln31_fu_648_p3;
reg   [3:0] select_ln31_reg_1359;
wire   [5:0] select_ln31_2_fu_666_p3;
reg   [5:0] select_ln31_2_reg_1366;
wire   [0:0] and_ln31_fu_686_p2;
reg   [0:0] and_ln31_reg_1371;
wire   [3:0] select_ln35_fu_709_p3;
reg   [3:0] select_ln35_reg_1378;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state12_pp0_stage3_iter1;
wire    ap_block_state20_pp0_stage3_iter2;
wire    ap_block_pp0_stage3_11001;
wire  signed [8:0] add_ln39_fu_902_p2;
reg  signed [8:0] add_ln39_reg_1390;
wire   [0:0] and_ln40_fu_914_p2;
reg   [0:0] and_ln40_reg_1395;
reg   [0:0] and_ln40_reg_1395_pp0_iter1_reg;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_state13_pp0_stage4_iter1;
wire    ap_block_pp0_stage4_11001;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state6_pp0_stage5_iter0;
wire    ap_block_state14_pp0_stage5_iter1;
wire    ap_block_pp0_stage5_11001;
wire   [17:0] grp_fu_1089_p4;
reg   [17:0] add_ln41_2_reg_1419;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_state7_pp0_stage6_iter0;
wire    ap_block_state15_pp0_stage6_iter1;
wire    ap_block_pp0_stage6_11001;
wire    ap_block_pp0_stage7_11001;
reg   [17:0] output_fm_addr_reg_1439;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state9_pp0_stage0_iter1;
wire    ap_block_state17_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
reg   [17:0] output_fm_addr_reg_1439_pp0_iter2_reg;
reg   [31:0] input_fm_load_reg_1449;
reg   [31:0] weights_load_reg_1454;
wire   [31:0] grp_fu_212_p2;
reg   [31:0] mul_reg_1469;
reg   [31:0] output_fm_load_reg_1474;
wire   [31:0] grp_fu_208_p2;
reg   [31:0] add_reg_1484;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage3_subdone;
wire   [63:0] zext_ln41_12_fu_1009_p1;
wire    ap_block_pp0_stage7;
wire   [63:0] zext_ln41_8_fu_1030_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln41_11_fu_1034_p1;
reg   [3:0] k_fu_126;
wire   [3:0] add_ln36_fu_962_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage2;
reg   [3:0] j_fu_130;
wire   [3:0] select_ln35_1_fu_935_p3;
reg   [7:0] indvar_flatten21_fu_134;
wire   [7:0] select_ln35_4_fu_1018_p3;
reg   [7:0] a_fu_138;
wire   [7:0] select_ln31_1_fu_803_p3;
reg   [12:0] indvar_flatten50_fu_142;
wire   [12:0] select_ln31_5_fu_972_p3;
wire    ap_block_pp0_stage1;
reg   [7:0] i_fu_146;
wire   [7:0] select_ln29_1_fu_757_p3;
reg   [18:0] indvar_flatten95_fu_150;
wire   [18:0] select_ln29_6_fu_984_p3;
reg   [1:0] m_fu_154;
reg   [20:0] indvar_flatten153_fu_158;
wire   [20:0] select_ln28_4_fu_1043_p3;
reg   [6:0] f_fu_162;
reg   [26:0] indvar_flatten221_fu_166;
wire    ap_block_pp0_stage4;
wire    ap_block_pp0_stage3;
wire   [31:0] grp_fu_208_p0;
wire    ap_block_pp0_stage6;
wire   [31:0] grp_fu_212_p0;
wire   [31:0] grp_fu_212_p1;
wire   [1:0] select_ln27_fu_313_p3;
wire   [1:0] add_ln28_fu_345_p2;
wire   [7:0] add_ln30_fu_379_p2;
wire   [7:0] add_ln34_fu_395_p2;
wire   [3:0] tmp_fu_411_p2;
wire  signed [8:0] tmp_cast_fu_417_p1;
wire   [8:0] zext_ln29_fu_375_p1;
wire   [0:0] tmp_1_fu_427_p3;
wire   [8:0] tmp_5_fu_453_p3;
wire   [9:0] zext_ln41_2_fu_461_p1;
wire   [9:0] zext_ln41_1_fu_449_p1;
wire   [9:0] sub_ln41_fu_465_p2;
wire   [0:0] icmp_ln36_fu_475_p2;
wire   [0:0] icmp_ln35_fu_486_p2;
wire  signed [10:0] sext_ln41_fu_471_p1;
wire   [10:0] zext_ln41_3_fu_509_p1;
wire  signed [10:0] add_ln41_fu_512_p2;
wire   [5:0] tmp_3_fu_385_p4;
wire   [0:0] xor_ln28_fu_530_p2;
wire   [0:0] and_ln27_1_fu_481_p2;
wire   [0:0] and_ln27_2_fu_492_p2;
wire   [0:0] and_ln27_3_fu_552_p2;
wire   [0:0] or_ln29_fu_568_p2;
wire   [5:0] p_mid_fu_586_p4;
wire   [5:0] select_ln28_2_fu_522_p3;
wire   [5:0] tmp_4_fu_401_p4;
wire   [0:0] and_ln28_1_fu_540_p2;
wire   [0:0] xor_ln29_fu_612_p2;
wire   [0:0] and_ln28_2_fu_546_p2;
wire   [0:0] or_ln31_fu_636_p2;
wire   [5:0] p_mid2_fu_656_p4;
wire   [5:0] select_ln29_3_fu_604_p3;
wire   [0:0] xor_ln31_fu_674_p2;
wire   [0:0] and_ln29_fu_618_p2;
wire   [0:0] or_ln31_2_fu_680_p2;
wire   [0:0] or_ln35_fu_692_p2;
wire   [0:0] or_ln35_1_fu_698_p2;
wire   [0:0] or_ln35_2_fu_704_p2;
wire   [6:0] mul_ln41_fu_733_p0;
wire   [6:0] mul_ln41_fu_733_p1;
wire   [0:0] and_ln27_fu_739_p2;
wire   [8:0] zext_ln29_1_fu_754_p1;
wire   [8:0] p_mid183_fu_769_p2;
wire   [8:0] select_ln28_3_fu_743_p3;
wire   [0:0] tmp_2_fu_782_p3;
wire   [0:0] rev34_fu_790_p2;
wire   [0:0] and_ln28_fu_749_p2;
wire   [8:0] select_ln29_2_cast_fu_762_p1;
wire   [8:0] p_mid142_fu_812_p2;
wire   [8:0] select_ln29_4_fu_775_p3;
wire   [0:0] tmp_6_fu_825_p3;
wire   [0:0] rev37_fu_833_p2;
wire   [0:0] select_ln29_5_fu_796_p3;
wire   [3:0] tmp_mid1_fu_846_p2;
wire  signed [8:0] tmp_cast_mid1_fu_851_p1;
wire   [8:0] p_mid1_fu_855_p2;
wire   [8:0] select_ln31_3_fu_818_p3;
wire  signed [8:0] select_ln35_2_fu_861_p3;
wire   [0:0] tmp_7_fu_872_p3;
wire   [0:0] rev40_fu_880_p2;
wire   [0:0] select_ln31_4_fu_839_p3;
wire   [3:0] add_ln39_1_fu_893_p2;
wire  signed [8:0] sext_ln39_fu_898_p1;
wire   [8:0] select_ln31_1_cast_fu_808_p1;
wire   [0:0] icmp_ln40_fu_908_p2;
wire   [0:0] select_ln35_3_fu_886_p3;
wire   [3:0] add_ln35_fu_930_p2;
wire  signed [10:0] grp_fu_1071_p3;
wire    ap_block_pp0_stage5;
wire  signed [13:0] grp_fu_1080_p3;
wire   [12:0] add_ln31_1_fu_967_p2;
wire   [18:0] add_ln29_1_fu_979_p2;
wire  signed [17:0] zext_ln41_12_fu_1009_p0;
wire   [17:0] grp_fu_1099_p3;
wire   [7:0] add_ln35_1_fu_1013_p2;
wire  signed [14:0] zext_ln41_11_fu_1034_p0;
wire   [14:0] grp_fu_1108_p3;
wire   [20:0] add_ln28_1_fu_1038_p2;
wire   [1:0] grp_fu_1071_p0;
wire   [7:0] grp_fu_1071_p1;
wire   [3:0] grp_fu_1080_p1;
wire   [3:0] grp_fu_1080_p2;
wire   [12:0] mul_ln41_fu_733_p2;
wire   [5:0] grp_fu_1089_p1;
wire   [5:0] grp_fu_1089_p2;
wire   [5:0] grp_fu_1089_p3;
wire   [7:0] grp_fu_1099_p1;
wire   [3:0] grp_fu_1108_p1;
wire   [3:0] grp_fu_1108_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage3;
reg    ap_idle_pp0_0to0;
reg   [7:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to2;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [9:0] grp_fu_1071_p00;
wire   [13:0] grp_fu_1080_p20;
wire   [12:0] grp_fu_1089_p10;
wire   [17:0] grp_fu_1089_p30;
wire   [14:0] grp_fu_1108_p20;
wire   [12:0] mul_ln41_fu_733_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

conv_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_208_p0),
    .din1(mul_reg_1469),
    .ce(1'b1),
    .dout(grp_fu_208_p2)
);

conv_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_212_p0),
    .din1(grp_fu_212_p1),
    .ce(1'b1),
    .dout(grp_fu_212_p2)
);

conv_mul_7ns_7ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 13 ))
mul_7ns_7ns_13_1_1_U9(
    .din0(mul_ln41_fu_733_p0),
    .din1(mul_ln41_fu_733_p1),
    .dout(mul_ln41_fu_733_p2)
);

conv_mac_muladd_2ns_8ns_9s_11_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 11 ))
mac_muladd_2ns_8ns_9s_11_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1071_p0),
    .din1(grp_fu_1071_p1),
    .din2(select_ln35_2_fu_861_p3),
    .ce(1'b1),
    .dout(grp_fu_1071_p3)
);

conv_mac_muladd_11s_4ns_4ns_14_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 14 ))
mac_muladd_11s_4ns_4ns_14_4_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln41_fu_512_p2),
    .din1(grp_fu_1080_p1),
    .din2(grp_fu_1080_p2),
    .ce(1'b1),
    .dout(grp_fu_1080_p3)
);

conv_ama_addmuladd_13ns_6ns_6ns_6ns_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 6 ),
    .din3_WIDTH( 6 ),
    .dout_WIDTH( 18 ))
ama_addmuladd_13ns_6ns_6ns_6ns_18_4_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_ln41_fu_733_p2),
    .din1(grp_fu_1089_p1),
    .din2(grp_fu_1089_p2),
    .din3(grp_fu_1089_p3),
    .ce(1'b1),
    .dout(grp_fu_1089_p4)
);

conv_mac_muladd_11s_8ns_9s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mac_muladd_11s_8ns_9s_18_4_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1071_p3),
    .din1(grp_fu_1099_p1),
    .din2(add_ln39_reg_1390),
    .ce(1'b1),
    .dout(grp_fu_1099_p3)
);

conv_mac_muladd_14s_4ns_4ns_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 15 ))
mac_muladd_14s_4ns_4ns_15_4_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1080_p3),
    .din1(grp_fu_1108_p1),
    .din2(grp_fu_1108_p2),
    .ce(1'b1),
    .dout(grp_fu_1108_p3)
);

conv_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage7),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage7)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_fu_138 <= 8'd4;
    end else if (((icmp_ln27_reg_1209 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        a_fu_138 <= select_ln31_1_fu_803_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage3))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        f_fu_162 <= 7'd0;
    end else if (((icmp_ln27_reg_1209 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        f_fu_162 <= select_ln27_1_fu_444_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_fu_146 <= 8'd4;
    end else if (((icmp_ln27_reg_1209 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        i_fu_146 <= select_ln29_1_fu_757_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten153_fu_158 <= 21'd0;
        end else if (((icmp_ln27_reg_1209 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten153_fu_158 <= select_ln28_4_fu_1043_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten21_fu_134 <= 8'd0;
    end else if (((icmp_ln27_reg_1209 == 1'd0) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        indvar_flatten21_fu_134 <= select_ln35_4_fu_1018_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten221_fu_166 <= 27'd0;
    end else if (((icmp_ln27_reg_1209 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        indvar_flatten221_fu_166 <= add_ln27_1_reg_1213;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten50_fu_142 <= 13'd0;
    end else if (((icmp_ln27_reg_1209 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        indvar_flatten50_fu_142 <= select_ln31_5_fu_972_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten95_fu_150 <= 19'd0;
    end else if (((icmp_ln27_reg_1209 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        indvar_flatten95_fu_150 <= select_ln29_6_fu_984_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_fu_130 <= 4'd0;
    end else if (((icmp_ln27_reg_1209 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        j_fu_130 <= select_ln35_1_fu_935_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_fu_126 <= 4'd0;
    end else if (((icmp_ln27_reg_1209 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        k_fu_126 <= add_ln36_fu_962_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_fu_154 <= 2'd0;
    end else if (((icmp_ln27_reg_1209 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        m_fu_154 <= select_ln28_1_reg_1262;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln27_1_reg_1213 <= add_ln27_1_fu_289_p2;
        icmp_ln27_reg_1209 <= icmp_ln27_fu_283_p2;
        icmp_ln27_reg_1209_pp0_iter1_reg <= icmp_ln27_reg_1209;
        indvar_flatten153_load_reg_1204 <= indvar_flatten153_fu_158;
        indvar_flatten50_load_reg_1194 <= indvar_flatten50_fu_142;
        indvar_flatten95_load_reg_1199 <= indvar_flatten95_fu_150;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_fu_283_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln27_reg_1223 <= add_ln27_fu_301_p2;
        and_ln27_4_reg_1256 <= and_ln27_4_fu_339_p2;
        f_load_reg_1218 <= f_fu_162;
        icmp_ln28_reg_1228 <= icmp_ln28_fu_307_p2;
        icmp_ln29_reg_1251 <= icmp_ln29_fu_333_p2;
        icmp_ln31_reg_1246 <= icmp_ln31_fu_327_p2;
        select_ln28_1_reg_1262 <= select_ln28_1_fu_351_p3;
        xor_ln27_reg_1238 <= xor_ln27_fu_321_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_reg_1209 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln29_reg_1321 <= add_ln29_fu_562_p2;
        add_ln31_reg_1349 <= add_ln31_fu_630_p2;
        and_ln28_3_reg_1314 <= and_ln28_3_fu_556_p2;
        and_ln29_1_reg_1342 <= and_ln29_1_fu_624_p2;
        and_ln31_reg_1371 <= and_ln31_fu_686_p2;
        or_ln28_1_reg_1309 <= or_ln28_1_fu_535_p2;
        or_ln28_reg_1293 <= or_ln28_fu_497_p2;
        or_ln29_1_reg_1327 <= or_ln29_1_fu_573_p2;
        or_ln31_1_reg_1354 <= or_ln31_1_fu_642_p2;
        select_ln27_1_reg_1288 <= select_ln27_1_fu_444_p3;
        select_ln28_reg_1299 <= select_ln28_fu_501_p3;
        select_ln29_2_reg_1337 <= select_ln29_2_fu_596_p3;
        select_ln29_reg_1332 <= select_ln29_fu_578_p3;
        select_ln31_2_reg_1366 <= select_ln31_2_fu_666_p3;
        select_ln31_reg_1359 <= select_ln31_fu_648_p3;
        select_ln35_reg_1378 <= select_ln35_fu_709_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_reg_1209 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_ln39_reg_1390 <= add_ln39_fu_902_p2;
        and_ln40_reg_1395 <= and_ln40_fu_914_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_reg_1209 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        add_ln41_2_reg_1419 <= grp_fu_1089_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln40_reg_1395_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_reg_1484 <= grp_fu_208_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        and_ln40_reg_1395_pp0_iter1_reg <= and_ln40_reg_1395;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        empty_reg_1278 <= empty_fu_421_p2;
        indvar_flatten21_load_reg_1273 <= indvar_flatten21_fu_134;
        rev_reg_1283 <= rev_fu_435_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln40_reg_1395) & (icmp_ln27_reg_1209 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_fm_load_reg_1449 <= input_fm_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln40_reg_1395_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        mul_reg_1469 <= grp_fu_212_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_reg_1209 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_fm_addr_reg_1439 <= zext_ln41_8_fu_1030_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_fm_addr_reg_1439_pp0_iter2_reg <= output_fm_addr_reg_1439;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln40_reg_1395_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        output_fm_load_reg_1474 <= output_fm_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln40_reg_1395) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        weights_load_reg_1454 <= weights_q0;
    end
end

always @ (*) begin
    if (((icmp_ln27_reg_1209 == 1'd1) & (1'b0 == ap_block_pp0_stage7_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (icmp_ln27_reg_1209_pp0_iter1_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage7_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        input_fm_ce0 = 1'b1;
    end else begin
        input_fm_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        output_fm_address0 = output_fm_addr_reg_1439_pp0_iter2_reg;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        output_fm_address0 = output_fm_addr_reg_1439;
    end else begin
        output_fm_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        output_fm_ce0 = 1'b1;
    end else begin
        output_fm_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln40_reg_1395_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        output_fm_we0 = 1'b1;
    end else begin
        output_fm_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_ce0 = 1'b1;
    end else begin
        weights_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_idle_pp0_1to2 == 1'b1) & (ap_start_int == 1'b0)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage3))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln27_1_fu_289_p2 = (indvar_flatten221_fu_166 + 27'd1);

assign add_ln27_fu_301_p2 = (f_fu_162 + 7'd1);

assign add_ln28_1_fu_1038_p2 = (indvar_flatten153_load_reg_1204 + 21'd1);

assign add_ln28_fu_345_p2 = (select_ln27_fu_313_p3 + 2'd1);

assign add_ln29_1_fu_979_p2 = (indvar_flatten95_load_reg_1199 + 19'd1);

assign add_ln29_fu_562_p2 = (select_ln28_fu_501_p3 + 8'd4);

assign add_ln30_fu_379_p2 = ($signed(i_fu_146) + $signed(8'd252));

assign add_ln31_1_fu_967_p2 = (indvar_flatten50_load_reg_1194 + 13'd1);

assign add_ln31_fu_630_p2 = (select_ln29_fu_578_p3 + 8'd4);

assign add_ln34_fu_395_p2 = ($signed(a_fu_138) + $signed(8'd252));

assign add_ln35_1_fu_1013_p2 = (indvar_flatten21_load_reg_1273 + 8'd1);

assign add_ln35_fu_930_p2 = (select_ln31_reg_1359 + 4'd1);

assign add_ln36_fu_962_p2 = (select_ln35_reg_1378 + 4'd1);

assign add_ln39_1_fu_893_p2 = ($signed(select_ln35_reg_1378) + $signed(4'd11));

assign add_ln39_fu_902_p2 = ($signed(sext_ln39_fu_898_p1) + $signed(select_ln31_1_cast_fu_808_p1));

assign add_ln41_fu_512_p2 = ($signed(sext_ln41_fu_471_p1) + $signed(zext_ln41_3_fu_509_p1));

assign and_ln27_1_fu_481_p2 = (xor_ln27_reg_1238 & icmp_ln36_fu_475_p2);

assign and_ln27_2_fu_492_p2 = (xor_ln27_reg_1238 & icmp_ln35_fu_486_p2);

assign and_ln27_3_fu_552_p2 = (xor_ln27_reg_1238 & icmp_ln31_reg_1246);

assign and_ln27_4_fu_339_p2 = (xor_ln27_fu_321_p2 & icmp_ln29_fu_333_p2);

assign and_ln27_fu_739_p2 = (xor_ln27_reg_1238 & rev_reg_1283);

assign and_ln28_1_fu_540_p2 = (or_ln28_1_fu_535_p2 & and_ln27_1_fu_481_p2);

assign and_ln28_2_fu_546_p2 = (or_ln28_1_fu_535_p2 & and_ln27_2_fu_492_p2);

assign and_ln28_3_fu_556_p2 = (or_ln28_1_fu_535_p2 & and_ln27_3_fu_552_p2);

assign and_ln28_fu_749_p2 = (or_ln28_1_reg_1309 & and_ln27_fu_739_p2);

assign and_ln29_1_fu_624_p2 = (xor_ln29_fu_612_p2 & and_ln28_2_fu_546_p2);

assign and_ln29_fu_618_p2 = (xor_ln29_fu_612_p2 & and_ln28_1_fu_540_p2);

assign and_ln31_fu_686_p2 = (or_ln31_2_fu_680_p2 & and_ln29_fu_618_p2);

assign and_ln40_fu_914_p2 = (select_ln35_3_fu_886_p3 & icmp_ln40_fu_908_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage5_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage6_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage7_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage7_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage7;

assign empty_fu_421_p2 = ($signed(tmp_cast_fu_417_p1) + $signed(zext_ln29_fu_375_p1));

assign grp_fu_1071_p0 = grp_fu_1071_p00;

assign grp_fu_1071_p00 = select_ln28_1_fu_351_p3;

assign grp_fu_1071_p1 = 10'd226;

assign grp_fu_1080_p1 = 14'd11;

assign grp_fu_1080_p2 = grp_fu_1080_p20;

assign grp_fu_1080_p20 = select_ln35_1_fu_935_p3;

assign grp_fu_1089_p1 = grp_fu_1089_p10;

assign grp_fu_1089_p10 = select_ln29_2_reg_1337;

assign grp_fu_1089_p2 = 18'd55;

assign grp_fu_1089_p3 = grp_fu_1089_p30;

assign grp_fu_1089_p30 = select_ln31_2_reg_1366;

assign grp_fu_1099_p1 = 18'd226;

assign grp_fu_1108_p1 = 15'd11;

assign grp_fu_1108_p2 = grp_fu_1108_p20;

assign grp_fu_1108_p20 = select_ln35_reg_1378;

assign grp_fu_208_p0 = output_fm_load_reg_1474;

assign grp_fu_212_p0 = weights_load_reg_1454;

assign grp_fu_212_p1 = input_fm_load_reg_1449;

assign icmp_ln27_fu_283_p2 = ((indvar_flatten221_fu_166 == 27'd70276800) ? 1'b1 : 1'b0);

assign icmp_ln28_fu_307_p2 = ((indvar_flatten153_fu_158 == 21'd1098075) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_333_p2 = ((indvar_flatten95_fu_150 == 19'd366025) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_327_p2 = ((indvar_flatten50_fu_142 == 13'd6655) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_486_p2 = ((indvar_flatten21_fu_134 == 8'd121) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_475_p2 = ((k_fu_126 == 4'd11) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_908_p2 = ((add_ln39_fu_902_p2 < 9'd226) ? 1'b1 : 1'b0);

assign input_fm_address0 = zext_ln41_12_fu_1009_p1;

assign mul_ln41_fu_733_p0 = mul_ln41_fu_733_p00;

assign mul_ln41_fu_733_p00 = select_ln27_1_reg_1288;

assign mul_ln41_fu_733_p1 = 13'd55;

assign or_ln28_1_fu_535_p2 = (xor_ln28_fu_530_p2 | icmp_ln28_reg_1228);

assign or_ln28_fu_497_p2 = (icmp_ln28_reg_1228 | and_ln27_4_reg_1256);

assign or_ln29_1_fu_573_p2 = (or_ln29_fu_568_p2 | icmp_ln28_reg_1228);

assign or_ln29_fu_568_p2 = (and_ln28_3_fu_556_p2 | and_ln27_4_reg_1256);

assign or_ln31_1_fu_642_p2 = (or_ln31_fu_636_p2 | and_ln29_1_fu_624_p2);

assign or_ln31_2_fu_680_p2 = (xor_ln31_fu_674_p2 | and_ln28_3_fu_556_p2);

assign or_ln31_fu_636_p2 = (or_ln28_fu_497_p2 | and_ln28_3_fu_556_p2);

assign or_ln35_1_fu_698_p2 = (or_ln35_fu_692_p2 | or_ln29_fu_568_p2);

assign or_ln35_2_fu_704_p2 = (or_ln35_1_fu_698_p2 | icmp_ln28_reg_1228);

assign or_ln35_fu_692_p2 = (and_ln31_fu_686_p2 | and_ln29_1_fu_624_p2);

assign output_fm_d0 = add_reg_1484;

assign p_mid142_fu_812_p2 = ($signed(select_ln29_2_cast_fu_762_p1) + $signed(9'd507));

assign p_mid183_fu_769_p2 = ($signed(zext_ln29_1_fu_754_p1) + $signed(9'd507));

assign p_mid1_fu_855_p2 = ($signed(tmp_cast_mid1_fu_851_p1) + $signed(select_ln29_2_cast_fu_762_p1));

assign p_mid2_fu_656_p4 = {{select_ln29_fu_578_p3[7:2]}};

assign p_mid_fu_586_p4 = {{select_ln28_fu_501_p3[7:2]}};

assign rev34_fu_790_p2 = (tmp_2_fu_782_p3 ^ 1'd1);

assign rev37_fu_833_p2 = (tmp_6_fu_825_p3 ^ 1'd1);

assign rev40_fu_880_p2 = (tmp_7_fu_872_p3 ^ 1'd1);

assign rev_fu_435_p2 = (tmp_1_fu_427_p3 ^ 1'd1);

assign select_ln27_1_fu_444_p3 = ((icmp_ln28_reg_1228[0:0] == 1'b1) ? add_ln27_reg_1223 : f_load_reg_1218);

assign select_ln27_fu_313_p3 = ((icmp_ln28_fu_307_p2[0:0] == 1'b1) ? 2'd0 : m_fu_154);

assign select_ln28_1_fu_351_p3 = ((and_ln27_4_fu_339_p2[0:0] == 1'b1) ? add_ln28_fu_345_p2 : select_ln27_fu_313_p3);

assign select_ln28_2_fu_522_p3 = ((or_ln28_fu_497_p2[0:0] == 1'b1) ? 6'd0 : tmp_3_fu_385_p4);

assign select_ln28_3_fu_743_p3 = ((or_ln28_reg_1293[0:0] == 1'b1) ? 9'd511 : empty_reg_1278);

assign select_ln28_4_fu_1043_p3 = ((icmp_ln28_reg_1228[0:0] == 1'b1) ? 21'd1 : add_ln28_1_fu_1038_p2);

assign select_ln28_fu_501_p3 = ((or_ln28_fu_497_p2[0:0] == 1'b1) ? 8'd4 : i_fu_146);

assign select_ln29_1_fu_757_p3 = ((and_ln28_3_reg_1314[0:0] == 1'b1) ? add_ln29_reg_1321 : select_ln28_reg_1299);

assign select_ln29_2_cast_fu_762_p1 = select_ln29_1_fu_757_p3;

assign select_ln29_2_fu_596_p3 = ((and_ln28_3_fu_556_p2[0:0] == 1'b1) ? p_mid_fu_586_p4 : select_ln28_2_fu_522_p3);

assign select_ln29_3_fu_604_p3 = ((or_ln29_1_fu_573_p2[0:0] == 1'b1) ? 6'd0 : tmp_4_fu_401_p4);

assign select_ln29_4_fu_775_p3 = ((and_ln28_3_reg_1314[0:0] == 1'b1) ? p_mid183_fu_769_p2 : select_ln28_3_fu_743_p3);

assign select_ln29_5_fu_796_p3 = ((and_ln28_3_reg_1314[0:0] == 1'b1) ? rev34_fu_790_p2 : and_ln28_fu_749_p2);

assign select_ln29_6_fu_984_p3 = ((or_ln28_reg_1293[0:0] == 1'b1) ? 19'd1 : add_ln29_1_fu_979_p2);

assign select_ln29_fu_578_p3 = ((or_ln29_1_fu_573_p2[0:0] == 1'b1) ? 8'd4 : a_fu_138);

assign select_ln31_1_cast_fu_808_p1 = select_ln31_1_fu_803_p3;

assign select_ln31_1_fu_803_p3 = ((and_ln29_1_reg_1342[0:0] == 1'b1) ? add_ln31_reg_1349 : select_ln29_reg_1332);

assign select_ln31_2_fu_666_p3 = ((and_ln29_1_fu_624_p2[0:0] == 1'b1) ? p_mid2_fu_656_p4 : select_ln29_3_fu_604_p3);

assign select_ln31_3_fu_818_p3 = ((and_ln29_1_reg_1342[0:0] == 1'b1) ? p_mid142_fu_812_p2 : select_ln29_4_fu_775_p3);

assign select_ln31_4_fu_839_p3 = ((and_ln29_1_reg_1342[0:0] == 1'b1) ? rev37_fu_833_p2 : select_ln29_5_fu_796_p3);

assign select_ln31_5_fu_972_p3 = ((or_ln29_1_reg_1327[0:0] == 1'b1) ? 13'd1 : add_ln31_1_fu_967_p2);

assign select_ln31_fu_648_p3 = ((or_ln31_1_fu_642_p2[0:0] == 1'b1) ? 4'd0 : j_fu_130);

assign select_ln35_1_fu_935_p3 = ((and_ln31_reg_1371[0:0] == 1'b1) ? add_ln35_fu_930_p2 : select_ln31_reg_1359);

assign select_ln35_2_fu_861_p3 = ((and_ln31_reg_1371[0:0] == 1'b1) ? p_mid1_fu_855_p2 : select_ln31_3_fu_818_p3);

assign select_ln35_3_fu_886_p3 = ((and_ln31_reg_1371[0:0] == 1'b1) ? rev40_fu_880_p2 : select_ln31_4_fu_839_p3);

assign select_ln35_4_fu_1018_p3 = ((or_ln31_1_reg_1354[0:0] == 1'b1) ? 8'd1 : add_ln35_1_fu_1013_p2);

assign select_ln35_fu_709_p3 = ((or_ln35_2_fu_704_p2[0:0] == 1'b1) ? 4'd0 : k_fu_126);

assign sext_ln39_fu_898_p1 = $signed(add_ln39_1_fu_893_p2);

assign sext_ln41_fu_471_p1 = $signed(sub_ln41_fu_465_p2);

assign sub_ln41_fu_465_p2 = (zext_ln41_2_fu_461_p1 - zext_ln41_1_fu_449_p1);

assign tmp_1_fu_427_p3 = empty_fu_421_p2[32'd8];

assign tmp_2_fu_782_p3 = p_mid183_fu_769_p2[32'd8];

assign tmp_3_fu_385_p4 = {{add_ln30_fu_379_p2[7:2]}};

assign tmp_4_fu_401_p4 = {{add_ln34_fu_395_p2[7:2]}};

assign tmp_5_fu_453_p3 = {{select_ln27_1_fu_444_p3}, {2'd0}};

assign tmp_6_fu_825_p3 = p_mid142_fu_812_p2[32'd8];

assign tmp_7_fu_872_p3 = p_mid1_fu_855_p2[32'd8];

assign tmp_cast_fu_417_p1 = $signed(tmp_fu_411_p2);

assign tmp_cast_mid1_fu_851_p1 = $signed(tmp_mid1_fu_846_p2);

assign tmp_fu_411_p2 = ($signed(j_fu_130) + $signed(4'd11));

assign tmp_mid1_fu_846_p2 = ($signed(select_ln31_reg_1359) + $signed(4'd12));

assign weights_address0 = zext_ln41_11_fu_1034_p1;

assign xor_ln27_fu_321_p2 = (icmp_ln28_fu_307_p2 ^ 1'd1);

assign xor_ln28_fu_530_p2 = (icmp_ln29_reg_1251 ^ 1'd1);

assign xor_ln29_fu_612_p2 = (1'd1 ^ and_ln28_3_fu_556_p2);

assign xor_ln31_fu_674_p2 = (1'd1 ^ and_ln28_2_fu_546_p2);

assign zext_ln29_1_fu_754_p1 = add_ln29_reg_1321;

assign zext_ln29_fu_375_p1 = i_fu_146;

assign zext_ln41_11_fu_1034_p0 = grp_fu_1108_p3;

assign zext_ln41_11_fu_1034_p1 = $unsigned(zext_ln41_11_fu_1034_p0);

assign zext_ln41_12_fu_1009_p0 = grp_fu_1099_p3;

assign zext_ln41_12_fu_1009_p1 = $unsigned(zext_ln41_12_fu_1009_p0);

assign zext_ln41_1_fu_449_p1 = select_ln27_1_fu_444_p3;

assign zext_ln41_2_fu_461_p1 = tmp_5_fu_453_p3;

assign zext_ln41_3_fu_509_p1 = select_ln28_1_reg_1262;

assign zext_ln41_8_fu_1030_p1 = add_ln41_2_reg_1419;

endmodule //conv_conv_Pipeline_VITIS_LOOP_27_4_VITIS_LOOP_29_6_VITIS_LOOP_35_8_VITIS_LOOP_36_9
