// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module matmul_matmul_Pipeline_VITIS_LOOP_41_5_VITIS_LOOP_43_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Matrix_C_BRAM_V_address0,
        Matrix_C_BRAM_V_ce0,
        Matrix_C_BRAM_V_we0,
        Matrix_C_BRAM_V_d0,
        Matrix_C_BRAM_V_address1,
        Matrix_C_BRAM_V_ce1,
        Matrix_C_BRAM_V_we1,
        Matrix_C_BRAM_V_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [14:0] Matrix_C_BRAM_V_address0;
output   Matrix_C_BRAM_V_ce0;
output   Matrix_C_BRAM_V_we0;
output  [15:0] Matrix_C_BRAM_V_d0;
output  [14:0] Matrix_C_BRAM_V_address1;
output   Matrix_C_BRAM_V_ce1;
output   Matrix_C_BRAM_V_we1;
output  [15:0] Matrix_C_BRAM_V_d1;

reg ap_idle;
reg Matrix_C_BRAM_V_ce0;
reg Matrix_C_BRAM_V_we0;
reg Matrix_C_BRAM_V_ce1;
reg Matrix_C_BRAM_V_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln41_fu_101_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [7:0] select_ln41_fu_131_p3;
reg   [7:0] select_ln41_reg_234;
wire    ap_block_pp0_stage0_11001;
wire   [14:0] mul_ln47_fu_151_p2;
reg   [14:0] mul_ln47_reg_240;
wire   [63:0] zext_ln47_2_fu_186_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln47_4_fu_205_p1;
reg   [7:0] c_fu_44;
wire   [7:0] add_ln43_fu_157_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_c_load;
reg   [6:0] r_fu_48;
wire   [6:0] select_ln41_1_fu_139_p3;
reg   [6:0] ap_sig_allocacmp_r_load;
reg   [13:0] indvar_flatten13_fu_52;
wire   [13:0] add_ln41_1_fu_107_p2;
reg   [13:0] ap_sig_allocacmp_indvar_flatten13_load;
wire   [0:0] icmp_ln43_fu_125_p2;
wire   [6:0] add_ln41_fu_119_p2;
wire   [6:0] mul_ln47_fu_151_p0;
wire   [8:0] mul_ln47_fu_151_p1;
wire   [14:0] zext_ln47_1_fu_178_p1;
wire   [14:0] add_ln47_fu_181_p2;
wire   [7:0] or_ln43_fu_191_p2;
wire   [14:0] zext_ln47_3_fu_196_p1;
wire   [14:0] add_ln47_1_fu_200_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [14:0] mul_ln47_fu_151_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

matmul_mul_7ns_9ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 15 ))
mul_7ns_9ns_15_1_1_U11(
    .din0(mul_ln47_fu_151_p0),
    .din1(mul_ln47_fu_151_p1),
    .dout(mul_ln47_fu_151_p2)
);

matmul_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln41_fu_101_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_44 <= add_ln43_fu_157_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_44 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln41_fu_101_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten13_fu_52 <= add_ln41_1_fu_107_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten13_fu_52 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln41_fu_101_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            r_fu_48 <= select_ln41_1_fu_139_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            r_fu_48 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln41_fu_101_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_ln47_reg_240 <= mul_ln47_fu_151_p2;
        select_ln41_reg_234 <= select_ln41_fu_131_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Matrix_C_BRAM_V_ce0 = 1'b1;
    end else begin
        Matrix_C_BRAM_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Matrix_C_BRAM_V_ce1 = 1'b1;
    end else begin
        Matrix_C_BRAM_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Matrix_C_BRAM_V_we0 = 1'b1;
    end else begin
        Matrix_C_BRAM_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Matrix_C_BRAM_V_we1 = 1'b1;
    end else begin
        Matrix_C_BRAM_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_101_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c_load = 8'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_44;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten13_load = 14'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten13_load = indvar_flatten13_fu_52;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_r_load = 7'd0;
    end else begin
        ap_sig_allocacmp_r_load = r_fu_48;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Matrix_C_BRAM_V_address0 = zext_ln47_4_fu_205_p1;

assign Matrix_C_BRAM_V_address1 = zext_ln47_2_fu_186_p1;

assign Matrix_C_BRAM_V_d0 = 16'd0;

assign Matrix_C_BRAM_V_d1 = 16'd0;

assign add_ln41_1_fu_107_p2 = (ap_sig_allocacmp_indvar_flatten13_load + 14'd1);

assign add_ln41_fu_119_p2 = (ap_sig_allocacmp_r_load + 7'd1);

assign add_ln43_fu_157_p2 = (select_ln41_fu_131_p3 + 8'd2);

assign add_ln47_1_fu_200_p2 = (mul_ln47_reg_240 + zext_ln47_3_fu_196_p1);

assign add_ln47_fu_181_p2 = (mul_ln47_reg_240 + zext_ln47_1_fu_178_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln41_fu_101_p2 = ((ap_sig_allocacmp_indvar_flatten13_load == 14'd10000) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_125_p2 = ((ap_sig_allocacmp_c_load < 8'd200) ? 1'b1 : 1'b0);

assign mul_ln47_fu_151_p0 = mul_ln47_fu_151_p00;

assign mul_ln47_fu_151_p00 = select_ln41_1_fu_139_p3;

assign mul_ln47_fu_151_p1 = 15'd200;

assign or_ln43_fu_191_p2 = (select_ln41_reg_234 | 8'd1);

assign select_ln41_1_fu_139_p3 = ((icmp_ln43_fu_125_p2[0:0] == 1'b1) ? ap_sig_allocacmp_r_load : add_ln41_fu_119_p2);

assign select_ln41_fu_131_p3 = ((icmp_ln43_fu_125_p2[0:0] == 1'b1) ? ap_sig_allocacmp_c_load : 8'd0);

assign zext_ln47_1_fu_178_p1 = select_ln41_reg_234;

assign zext_ln47_2_fu_186_p1 = add_ln47_fu_181_p2;

assign zext_ln47_3_fu_196_p1 = or_ln43_fu_191_p2;

assign zext_ln47_4_fu_205_p1 = add_ln47_1_fu_200_p2;

endmodule //matmul_matmul_Pipeline_VITIS_LOOP_41_5_VITIS_LOOP_43_6
