# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ykim131_588fa26/Desktop/ECE588/ECE588_fa2026_Lab03/vivado/Matrix_optim/Matrix_optim.srcs/sources_1/bd/matrix/ip/matrix_matmul_0_0/matrix_matmul_0_0.xci
# IP: The module: 'matrix_matmul_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ykim131_588fa26/Desktop/ECE588/ECE588_fa2026_Lab03/vivado/Matrix_optim/Matrix_optim.gen/sources_1/bd/matrix/ip/matrix_matmul_0_0/constraints/matmul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matrix_matmul_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/ykim131_588fa26/Desktop/ECE588/ECE588_fa2026_Lab03/vivado/Matrix_optim/Matrix_optim.srcs/sources_1/bd/matrix/ip/matrix_matmul_0_0/matrix_matmul_0_0.xci
# IP: The module: 'matrix_matmul_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ykim131_588fa26/Desktop/ECE588/ECE588_fa2026_Lab03/vivado/Matrix_optim/Matrix_optim.gen/sources_1/bd/matrix/ip/matrix_matmul_0_0/constraints/matmul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matrix_matmul_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
